"""Official OWASP Top 10 for Agentic Applications 2026 (ASI01-ASI10).

Source: docs/OWASP-Top-10-for-Agentic-Applications-2026-12.6-1.pdf (57 pages),
published December 9, 2025 by the OWASP GenAI Security Project (peer-reviewed,
100+ contributors). Content is CC BY-SA 4.0. Titles and risk descriptions are
verbatim from the official document; line-wrap hyphenation and spacing
artifacts from pdftotext extraction were resolved (2026-08-13).
"""


OWASP_AGENTIC_TOP_10_TITLES: dict[str, str] = {
    "ASI01": "Agent Goal Hijack",
    "ASI02": "Tool Misuse and Exploitation",
    "ASI03": "Identity and Privilege Abuse",
    "ASI04": "Agentic Supply Chain Vulnerabilities",
    "ASI05": "Unexpected Code Execution (RCE)",
    "ASI06": "Memory & Context Poisoning",
    "ASI07": "Insecure Inter-Agent Communication",
    "ASI08": "Cascading Failures",
    "ASI09": "Human-Agent Trust Exploitation",
    "ASI10": "Rogue Agents",
}


OWASP_AGENTIC_TOP_10_DESCRIPTIONS: dict[str, str] = {
    "ASI01": "AI Agents exhibit autonomous ability to execute a series of tasks to achieve a goal. Due to inherent weaknesses in how natural-language instructions and related content are processed, agents and the underlying model cannot reliably distinguish instructions from related content. As a result, attackers can manipulate an agent’s objectives, task selection, or decision pathways through a variety of techniques - including, but not limited to, prompt-based manipulation, deceptive tool outputs, malicious artefacts, forged agent-to-agent messages, or poisoned external data. Because agents rely on untyped natural-language inputs and loosely governed orchestration logic, they cannot reliably distinguish legitimate instructions from attacker-controlled content. Unlike LLM01:2025, which focuses on altering a single model response, ASI01 captures the broader agentic impact where manipulated inputs redirect goals, planning (when used) and multi-step behavior. Agent Goal Hijack differs from ASI06 (Memory & Context Poisoning) and ASI10 (Rogue Agents) because the attacker directly alters the agent’s goals, instructions, or decision pathways - regardless of whether the manipulation occurs interactively or through pre-positioned inputs such as documents, templates, or external data sources. ASI06 focuses on the persistent corruption of stored context or long-term memory, while ASI10 captures autonomous misalignment that emerges without active attacker control. In the OWASP Agentic AI Threats & Mitigations Guide, ASI01 corresponds to T06 Goal Manipulation (altering the agent’s objectives) and T07 Misaligned & Deceptive Behaviors (bypassing safeguards or deceiving humans). Together, these illustrate how attackers can subvert the agent’s objectives and action-selection logic, redirecting its autonomy toward unintended or harmful outcomes.",
    "ASI02": "Agents can misuse legitimate tools due to prompt injection, misalignment, or unsafe delegation or ambiguous instruction - leading to data exfiltration, tool output manipulation or workflow hijacking. Risks arise from how the agent chooses and applies tools; agent memory, dynamic tool selection, and delegation can contribute to misuse via chaining, privilege escalation, and unintended actions. This relates to LLM06:2025 (Excessive Agency), which addresses excessive autonomy but focuses on the misuse of legitimate tools. This entry covers cases where the agent operates within its authorized privileges but applies a legitimate tool in an unsafe or unintended way - for example deleting valuable data, over-invoking costly APIs, or exfiltrating information. If the misuse involves privilege escalation or credential inheritance, it falls under ASI03 (Identity & Privilege Abuse); if the misuse results in arbitrary or injected code execution, it is classified under ASI05 (Unexpected Code Execution). Finally, tool definitions increasingly come via MCP servers, creating a natural overlap with ASI04 (Agentic Supply Chain Vulnerabilities). The entry maps to T2 Tool Misuse in the Agentic AI Threats and Mitigations Guide whilst T4 Resource Overload and T16 Insecure Inter-Agent Protocol Abuse represent contributing factors that can amplify or enable tool exploitation. The entry aligns with AIVSS Core Risk: Agentic AI Tool Misuse.",
    "ASI03": "Identity & Privilege Abuse exploits dynamic trust and delegation in agents to escalate access and bypass controls by manipulating delegation chains, role inheritance, control flows, and agent context; context includes cached credentials or conversation history across interconnected systems. In this context, identity refers both to the agent’s defined persona and to any authentication material that represents it. Agent-to- agent trust or inherited credentials can be exploited to escalate access, hijack privileges, or execute unauthorized actions. This risk arises from the architectural mismatch between user-centric identity systems and agentic design. Without a distinct, governed identity of its own, an agent operates in an attribution gap that makes enforcing true least privilege impossible. Identity in this context includes both the agent’s assigned persona and any authentication material (API keys, OAuth tokens, delegated user sessions) that represent it. This differs from ASI02 (Tools Misuse) which is an unintended or unsafe use of already granted privilege by a principal misusing its own tools. Identity & Privilege Abuse is the agentic evolution of Excessive Agency (LLM06:2025). It often leverages Prompt Injection (LLM01:2025), and because of agent permissions, tool integrations, and multi-agent systems, the impact can amplify and exceed Sensitive Information Disclosure (LLM02:2025) to directly compromise the confidentiality, integrity, and availability of systems and data the agent can reach. In the OWASP ASI Threats and Mitigations, it maps one-to-one to T3: Privilege Compromise, and in OWASP AIVSS it corresponds to Core Risk 2: Agent Access Control Violation.",
    "ASI04": "Agentic Supply Chain Vulnerabilities arise when agents, tools, and related artefacts they work with are provided by third parties and may be malicious, compromised, or tampered with in transit. These can be both static and dynamicallyly sourced components, including models and model weights, tools, plug-ins, datasets, other agents, agentic interfaces - MCP (Model Context Protocol), A2A (Agent2Agent) - agentic registries and related artifacts, or update channels. These dependencies may introduce unsafe code, hidden instructions, or deceptive behaviors into the agent’s execution chain. Supply chain is covered in depth in LLM03:2025 Supply Chain Vulnerabilities. However, its focus is on static dependencies. Unlike traditional AI or software supply chains, agentic ecosystems often compose capabilities at runtime - loading external tools and agent personas dynamically – thereby increasing the attack surface. This distributed run-time coordination - combined with agentic autonomy - creates a live supply chain that can cascade vulnerabilities across agents. These shifts focus from manifest to run-time security of a diverse and often opaque component. Tackling this problem requires careful development-time tooling and runtime orchestration, where components are dynamically loaded, shared, and trusted. The entry maps to T17 Supply Chain Compromise in Agentic Threats and Mitigations and across T2 Tool Misuse, T11 Unexpected RCE and Code Attacks, T12 Agent Communication Poisoning, T13 Rogue Agent and T16 Insecure Inter-Agent Protocol Abuse.",
    "ASI05": "Agentic systems - including popular vibe coding tools - often generate and execute code. Attackers exploit code-generation features or embedded tool access to escalate actions into remote code execution (RCE), local misuse, or exploitation of internal systems. Because this code is often generated in real-time by the agent it can bypass traditional security controls. Prompt injection, tool misuse, or unsafe serialization can convert text into unintended executable behavior. While code execution can be triggered via the same tool interfaces discussed under ASI02, ASI05 focuses on unexpected or adversarial execution of code (scripts, binaries, JIT/WASM modules, deserialized objects, template engines, in memory evaluations) that leads to host or container compromise, persistence, or sandbox escape - outcomes that require host and runtime-specific mitigations beyond ordinary tool-use controls. This entry builds on LLM01:2025 Prompt Injection and LLM05:2025 Improper Output Handling, reflecting their evolution in agentic systems from a single manipulated output interpreted or executed to orchestrated multi-tool chains that achieve execution through a sequence of otherwise legitimate tool calls. This risk aligns with T11 Unexpected RCE and Code Attacks in Agentic AI – Threats and Mitigations v1.1.",
    "ASI06": "Agentic systems rely on stored and retrievable information which can be a snapshot of its conversation history, a memory tool or expanded context, which supports continuity across tasks and reasoning cycles. Context includes any information an agent retains, retrieves, or reuses, such as summaries, embeddings, and RAG stores but excludes one-time input prompts covered under LLM01:2025 Prompt Injection. In Memory and Context Poisoning, adversaries corrupt or seed this context with malicious or misleading data, causing future reasoning, planning, or tool use to become biased, unsafe, or aid exfiltration. Ingestion sources such as uploads, API feeds, user input, or peer-agent exchanges may be untrusted or only partially validated. This risk is distinct from ASI01 (Goal Hijack), which captures direct goal manipulation, and ASI08 (Cascading Failures), which describes degradation after poisoning occurs. However, memory poisoning frequently leads to goal hijacking (ASI01), as corrupted context or long-term memory can alter the agent’s goal interpretation, reasoning path, or tool-selection logic. It builds on LLM01:2025 Prompt Injection, LLM04:2025 Data and Model Poisoning, and LLM08:2025 Vector and Embedding Weaknesses, but focuses on persistent corruption of agent memory and retrievable context that propagates across sessions and alters autonomous reasoning. It maps to T1 Memory Poisoning in Agentic Threats and Mitigations, with related impacts in T4 Memory Overload, T6 Broken Goals, and T12 Shared Memory Poisoning. In AIVSS, the AARS fields Memory Use and Contextual Awareness raise the agentic vulnerability score.",
    "ASI07": "Multi agent systems depend on continuous communication between autonomous agents that coordinate via APIs, message buses, and shared memory, significantly expanding the attack surface. Decentralized architecture, varying autonomy, and uneven trust make perimeter-based security models ineffective. Weak inter-agent controls for authentication, integrity, confidentiality, or authorization let attackers intercept, manipulate, spoof, or block messages. Insecure Inter-Agent Communication occurs when these exchanges lack proper authentication, integrity, or semantic validation, allowing interception, spoofing, or manipulation of agent messages and intents. The threat spans transport, routing, discovery, and semantic layers, including covert or side-channels where agents leak or infer data through timing or behavioral cues. This differs from ASI03 (Identity & Privilege Abuse), which focuses on credential and permissions misuse, and ASI06 (Memory & Context Poisoning), which targets stored knowledge corruption. ASI07 focuses on compromising real-time messages between agents, leading to misinformation, privilege confusion, or coordinated manipulation across distributed agentic systems. The entry is covered by T12 – Agent Communication Poisoning & T16 – Insecure Inter-Agent Protocol Abuse in Agentic Threats and Mitigations",
    "ASI08": "Agentic cascading failures occur when a single fault (hallucination, malicious input, corrupted tool, or poisoned memory) propagates across autonomous agents, compounding into system-wide harm. Because agents plan, persist, and delegate autonomously, a single error can bypass stepwise human checks and persist in a saved state. As agents form emergent links to new tools or peers, these latent faults chain into privileged operations that compromise confidentiality, integrity, availability, leading to widespread service failures across agent networks, systems, and workflows. Cascading Failures describes the propagation and amplification of an initial fault - not the initial vulnerability itself - across agents, tools, and workflows, turning a single error into system-wide impact. ASI08 focuses on the propagation and amplification of faults rather than their origin. Use the initial defect under ASI04, ASI06, or ASI07 when it represents a direct compromise - such as a tainted dependency, poisoned memory, or spoofed message - and apply ASI08 only when that defect spreads across agents, sessions, or workflows, causing measurable fan-out or systemic impact beyond the original breach. Observable symptoms include rapid fan-out where one faulty decision triggers many downstream agents or tasks in a short time, cross-domain or tenant spread beyond the original context, oscillating retries or feedback loops between agents, and downstream queue storms or repeated identical intents - each providing clear detection hooks that make ASI08 operationally actionable. Cascading failures amplify across interconnected agents, chaining OWASP LLM Top 10 risks. LLM01:2025 Prompt Injection and LLM06:2025 Excessive Agency can trigger autonomous tool runs that spread errors without human checks, while LLM04:2025 Data and Model Poisoning in persistent memory can skew decisions across sessions and workflows. Agentic AI - Threats and Mitigations 1.1 covers this threat in T5 – Cascading Hallucination Attacks while T8 – Repudiation and Untraceability highlights a fundamental defense: the ability to trace, attribute, and audit cascading behaviors through resilient logging and non-repudiation mechanisms that prevent silent propagation. However, these compounding threats illustrate a potential discrepancy in the speed and scale of fault propagation in a multi-agent system and the ability of humans to keep up with them to ensure secure and effective operation of the system. This leaves some unmitigated risks that the enterprise must evaluate carefully to ensure they are within the overall risk budget for the organization.",
    "ASI09": "Intelligent agents can establish strong trust with human users through their natural language fluency, emotional intelligence, and perceived expertise, known as anthropomorphism. Adversaries or misaligned designs may exploit this trust to influence user decisions, extract sensitive information, or steer outcomes for malicious purposes. In agentic systems, this risk is amplified when humans over-rely on autonomous recommendations or unverifiable rationales, approving actions without independent validation. By leveraging authority bias and persuasive explainability, attackers can bypass oversight, leading to data breaches, financial losses, downstream and reputational harms. The agent acts as an untraceable \"bad influence,\" manipulating the human into performing the final, audited action, making the agent's role in the compromise invisible to forensics. Automation bias, perceived authority, and anthropomorphic cues make abuse look legitimate and hard to spot. Over-reliance on agent recommendations, especially when they appear confident or authoritative, increases the chance of harmful decision-making. This entry is about human misperception or over-reliance whereas ASI10 is agent intent deviation. The entry builds on LLM06:2025 Excessive Agency, and can be caused by LLM01:2025 Prompt Injection, LLM05:2025 Improper Output Handling, or results in LLM09:2025 Misinformation. Aligns with Agentic AI Threats and Mitigations Guide (T7) Misaligned & Deceptive, (T8) Repudiation & Untraceability, (T10) Overwhelming the Human in the Loop.",
    "ASI10": "Rogue Agents are malicious or compromised AI Agents that deviate from their intended function or authorized scope, acting harmfully, deceptively, or parasitically within multi-agent or human-agent ecosystems. The agent’s actions may individually appear legitimate, but its emergent behavior becomes harmful, creating a containment gap for traditional rule-based systems. While external compromise, such as Prompt Injection (LLM01:2025), Goal Hijack (AS01) or Supply Chain tampering (AS04) can initiate the divergence, ASI10 focuses on the loss of behavioral integrity and governance once the drift begins, not the initial intrusion itself. Consequences include sensitive information disclosure, misinformation propagation, workflow hijacking, and operational sabotage. Rogue Agents represent a distinct risk of behavioral divergence, unlike Excessive Agency (LLM06:2025), which focuses on over-granted permissions, and can be amplified \"insider threats\" due to the speed and scale of Agentic systems. Consequences include Sensitive Information Disclosure (LLM02;2025), Misinformation (LLM09:2025). In the OWASP Agentic AI Threats and Mitigations guide, ASI10 corresponds to T13 – Rogue Agents in Multi-Agent Systems. The OWASP AIVSS framework maps this risk primarily to Behavioral Integrity (BI), Operational Security (OS), and Compliance Violations (CV), with elevated severity for critical or self-propagating deployments.",
}
