"""
controls.py — 110 CMMC / NIST SP 800-171 Rev 2 control catalog.

Families, SPRS weights, implementation guidance, and audit-ready descriptions.
Source: NIST SP 800-171 Rev 2 & DFARS 252.204-7020
"""

CMMC_FRAMEWORK = {
    # ACCESS CONTROL (AC) - 22 Controls
    "AC.L2-3.1.1": {"family": "Access Control", "name": "Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems)", "weight": 3, "description": "Access to systems is limited to authorized personnel through role-based access controls (RBAC) managed via Microsoft Entra ID or Active Directory. Regular access reviews are conducted quarterly."},
    "AC.L2-3.1.2": {"family": "Access Control", "name": "Limit system access to the types of transactions and functions that authorized users are permitted to execute", "weight": 3, "description": "Least privilege is enforced using application-level permissions (e.g., SharePoint access levels, Azure role assignments). Privileged functions are logged and monitored."},
    "AC.L2-3.1.3": {"family": "Access Control", "name": "Control the flow of CUI in accordance with approved authorizations", "weight": 1, "description": "Data flows are controlled via security groups and application-layer policies ensuring CUI does not traverse unapproved channels."},
    "AC.L2-3.1.4": {"family": "Access Control", "name": "Separate the duties of individuals to reduce the risk of malevolent activity without collusion", "weight": 3, "description": "Segregation of duties (SoD) policies are formalized in HR procedures. No single individual can both create and approve access requests."},
    "AC.L2-3.1.5": {"family": "Access Control", "name": "Employ the principle of least privilege, including for specific security functions and privileged accounts", "weight": 1, "description": "Privilege levels are defined in access matrix documentation. Default access is read-only; escalation requires business justification and approval."},
    "AC.L2-3.1.6": {"family": "Access Control", "name": "Use non-privileged accounts or roles when accessing nonsecurity functions", "weight": 3, "description": "Standard users operate with least-privilege accounts. Privileged access is via Just-In-Time (JIT) elevation tools (e.g., Azure PIM) with session logging enabled."},
    "AC.L2-3.1.7": {"family": "Access Control", "name": "Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs", "weight": 3, "description": "Execution policies enforced through UAC, AppLocker, or Endpoint Detection and Response tools. All elevation attempts are audit-logged."},
    "AC.L2-3.1.8": {"family": "Access Control", "name": "Limit unsuccessful logon attempts", "weight": 5, "description": "Account lockout thresholds are defined and enforced across domain and cloud accounts to limit unsuccessful logon attempts. Lockout parameters (threshold, observation window, and reset period) are configured per organizational policy."},
    "AC.L2-3.1.9": {"family": "Access Control", "name": "Provide privacy and security notices consistent with applicable CUI rules", "weight": 3, "description": "Logon banners stating unauthorized access is prohibited are enforced via GPO or cloud policy across all endpoints and administrative portals."},
    "AC.L2-3.1.10": {"family": "Access Control", "name": "Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity", "weight": 3, "description": "Workstations automatically lock after a defined period of inactivity. Session locking is enforced via native OS or MDM tools to prevent unauthorized access and viewing."},
    "AC.L2-3.1.11": {"family": "Access Control", "name": "Terminate (automatically) a user session after a defined condition", "weight": 3, "description": "RDP, SSH, and web sessions auto-terminate after a defined maximum idle period or at the end of business day."},
    "AC.L2-3.1.12": {"family": "Access Control", "name": "Monitor and control remote access sessions", "weight": 3, "description": "All remote access sessions are brokered through a secure VPN or Zero Trust gateway. Sessions are recorded via session recording or RDP proxy tools."},
    "AC.L2-3.1.13": {"family": "Access Control", "name": "Employ cryptographic mechanisms to protect the confidentiality of remote access sessions", "weight": 3, "description": "Remote access is encrypted using TLS 1.3 or IPsec with AES-256 GCM encryption. Certificate-based authentication is used for endpoints."},
    "AC.L2-3.1.14": {"family": "Access Control", "name": "Route remote access via managed access control points", "weight": 3, "description": "All external connections are routed through a centrally managed gateway (e.g., Zscaler, Azure Virtual WAN) with integrated access policy enforcement."},
    "AC.L2-3.1.15": {"family": "Access Control", "name": "Authorize remote execution of privileged commands and remote access to security-relevant information", "weight": 1, "description": "Remote privileged commands require multi-step approval. Use of privileged access is restricted and logged in SIEM or PAM system."},
    "AC.L2-3.1.16": {"family": "Access Control", "name": "Authorize wireless access prior to allowing such connections", "weight": 1, "description": "Wireless access must be approved by IT and configured under BYOD or corporate Wi-Fi policy, with periodic review of connected devices."},
    "AC.L2-3.1.17": {"family": "Access Control", "name": "Protect wireless access using authentication and encryption", "weight": 3, "description": "Wi-Fi networks use WPA3-Enterprise with EAP-TLS. Certificates are issued from internal PKI or Microsoft Entra-managed identities."},
    "AC.L2-3.1.18": {"family": "Access Control", "name": "Control connection of mobile devices", "weight": 3, "description": "Mobile device policy enforced via MDM solution. Devices must be enrolled and comply with organization security baselines prior to access."},
    "AC.L2-3.1.19": {"family": "Access Control", "name": "Encrypt CUI on mobile devices and mobile computing platforms", "weight": 3, "description": "Disk encryption enforced on laptops (BitLocker) and mobile devices (iOS FileVault / Android work profiles). Key escrow managed via HSM."},
    "AC.L2-3.1.20": {"family": "Access Control", "name": "Verify and control/limit connections to and use of external systems", "weight": 3, "description": "Shared resources (e.g., file shares, SharePoint libraries) require role-based access (RBAC). Periodic entitlement reviews are performed using access analytics."},
    "AC.L2-3.1.21": {"family": "Access Control", "name": "Limit use of portable storage devices on external systems", "weight": 3, "description": "USB storage access restricted via group policy or endpoint agent. Only approved encrypted media are allowed for offsite use (e.g., IronKey)."},
    "AC.L2-3.1.22": {"family": "Access Control", "name": "Control CUI posted or processed on publicly accessible systems", "weight": 3, "description": "Use of public systems (e.g., GitHub, SaaS apps) is regulated by policy and restricted via DLP or approval workflows. All CUI must be removed before sharing."},

    # AWARENESS AND TRAINING (AT) - 3 Controls
    "AT.L2-3.2.1": {"family": "Awareness and Training", "name": "Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems", "weight": 3, "description": "Annual CUI and phishing awareness training delivered via Learning Management System (LMS) or phishing simulation tools (e.g., KnowBe4)."},
    "AT.L2-3.2.2": {"family": "Awareness and Training", "name": "Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities", "weight": 3, "description": "Role-based training is provided for all IT roles. Certifications encouraged or required (e.g., Security+, CISSP, Azure Security Engineer)."},
    "AT.L2-3.2.3": {"family": "Awareness and Training", "name": "Provide security awareness training on recognizing and reporting potential indicators of insider threat", "weight": 3, "description": "Phishing simulations are conducted quarterly. Users report suspicious emails through integrated mailbox reporting tools. Simulated attacks result in follow-up coaching."},

    # AUDIT AND ACCOUNTABILITY (AU) - 9 Controls
    "AU.L2-3.3.1": {"family": "Audit and Accountability", "name": "Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity", "weight": 3, "description": "Audit logs captured via SIEM, directory services, or native OS logs. Logs retained per organizational retention policy and centrally managed. Regular review of critical logs performed."},
    "AU.L2-3.3.2": {"family": "Audit and Accountability", "name": "Ensure that the actions of individual system users can be uniquely traced to those users, so they can be held accountable for their actions", "weight": 3, "description": "All systems are registered in CMDB and tagged. Logs include username, IP, timestamp, and action for traceability. SSO ensures consistent identity."},
    "AU.L2-3.3.3": {"family": "Audit and Accountability", "name": "Review and update logged events", "weight": 3, "description": "Audit settings are reviewed during system baselining and updated when access patterns change. Configurations maintained via SCCM, Intune, or IaC tools."},
    "AU.L2-3.3.4": {"family": "Audit and Accountability", "name": "Alert in the event of an audit logging process failure", "weight": 5, "description": "Monitoring tools alert SOC or IT when logs stop ingesting. Escalation processes are defined and documented for unresolved logging failures."},
    "AU.L2-3.3.5": {"family": "Audit and Accountability", "name": "Correlate audit record review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity", "weight": 5, "description": "SIEM correlates logs with asset inventories and UEBA profiles to detect anomalies. Incidents are escalated via SOAR orchestration and IR playbooks."},
    "AU.L2-3.3.6": {"family": "Audit and Accountability", "name": "Provide audit record reduction and report generation to support on-demand analysis and reporting", "weight": 3, "description": "Audit record reduction and report generation tools are available to analyze audit logs. Tools support filtering, sorting, and correlation of audit data for on-demand analysis."},
    "AU.L2-3.3.7": {"family": "Audit and Accountability", "name": "Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records", "weight": 3, "description": "Systems synchronized to authoritative time source (e.g., NTP pool or internal stratum-1 server). Clock synchronization ensures consistent time stamps across all audit records."},
    "AU.L2-3.3.8": {"family": "Audit and Accountability", "name": "Protect audit information and audit logging tools from unauthorized access, modification, and deletion", "weight": 5, "description": "Audit logs and tools (e.g., Splunk, Sentinel) are protected using RBAC. Only security and audit team members have read/write access to audit data and logging infrastructure."},
    "AU.L2-3.3.9": {"family": "Audit and Accountability", "name": "Limit management of audit logging functionality to a subset of privileged users", "weight": 3, "description": "Only security administrators (e.g., SOC Tier 2) are granted audit configuration permissions. Changes to audit logging settings are logged with change management system."},

    # CONFIGURATION MANAGEMENT (CM) - 9 Controls
    "CM.L2-3.4.1": {"family": "Configuration Management", "name": "Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles", "weight": 3, "description": "CMDB tracks all assets. Baseline configurations enforced using SCCM, Intune, or cloud templates (ARM, Bicep). Baselines reviewed quarterly."},
    "CM.L2-3.4.2": {"family": "Configuration Management", "name": "Establish and enforce security configuration settings for information technology products employed in organizational systems", "weight": 3, "description": "SCCM or Azure Policy enforces security baselines. Security Technical Implementation Guides (STIGs) are applied to all OS endpoints and servers."},
    "CM.L2-3.4.3": {"family": "Configuration Management", "name": "Track, review, approve or disapprove, and log changes to organizational systems", "weight": 1, "description": "All changes submitted through change management portal. High-risk changes require CAB approval and rollback plan. Changes logged in audit trail."},
    "CM.L2-3.4.4": {"family": "Configuration Management", "name": "Analyze the security impact of changes prior to implementation", "weight": 3, "description": "Security impact analysis is performed during change requests. Includes review of threat models and dependency checks before deployment."},
    "CM.L2-3.4.5": {"family": "Configuration Management", "name": "Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems", "weight": 3, "description": "Change access enforced through RBAC in source repos and CI/CD pipelines. Admin jump hosts used for elevated changes with session recordings."},
    "CM.L2-3.4.6": {"family": "Configuration Management", "name": "Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities", "weight": 3, "description": "Unnecessary services disabled via group policy or configuration scripts. Application allowlisting ensures only approved binaries run."},
    "CM.L2-3.4.7": {"family": "Configuration Management", "name": "Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services", "weight": 5, "description": "Default-deny firewall policies applied. Endpoint agents (e.g., CrowdStrike, SentinelOne) restrict execution of unknown binaries."},
    "CM.L2-3.4.8": {"family": "Configuration Management", "name": "Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software", "weight": 3, "description": "Use of application allowlisting tools (AppLocker, Device Guard) prevents unauthorized software. Exceptions reviewed weekly."},
    "CM.L2-3.4.9": {"family": "Configuration Management", "name": "Control and monitor user-installed software", "weight": 1, "description": "User software installs restricted via AppLocker or MDM policies. Only IT-approved software available via software portal or App Store."},

    # IDENTIFICATION AND AUTHENTICATION (IA) - 11 Controls
    "IA.L2-3.5.1": {"family": "Identification and Authentication", "name": "Identify system users, processes acting on behalf of users, and devices", "weight": 3, "description": "All user accounts are uniquely identified in directory services. Devices are registered in Intune or MDM prior to system access."},
    "IA.L2-3.5.2": {"family": "Identification and Authentication", "name": "Authenticate (or verify) the identities of users, processes, or devices, as a prerequisite to allowing access to organizational systems", "weight": 3, "description": "Authentication via Entra ID or AD with MFA required. Devices authenticate via certificates or device-bound credentials."},
    "IA.L2-3.5.3": {"family": "Identification and Authentication", "name": "Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.[24] [25]", "weight": 3, "description": "All admin roles use FIDO2 or Microsoft Authenticator. Non-privileged remote access (VPN, O365) requires MFA. PIM used for Just-in-Time access."},
    "IA.L2-3.5.4": {"family": "Identification and Authentication", "name": "Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts", "weight": 3, "description": "Unique identifiers assigned per user. Passwords are rotated annually or upon reset. Account names are generic (not based on role)."},
    "IA.L2-3.5.5": {"family": "Identification and Authentication", "name": "Prevent reuse of identifiers for a defined period", "weight": 5, "description": "User ID reuse blocked in directory services. Historical tracking ensures no duplicate IDs are assigned after deactivation."},
    "IA.L2-3.5.6": {"family": "Identification and Authentication", "name": "Disable identifiers after a defined period of inactivity", "weight": 3, "description": "Accounts disabled after a defined period of inactivity. Review and notification sent to manager. Automated deactivation via HR integration or workflow."},
    "IA.L2-3.5.7": {"family": "Identification and Authentication", "name": "Enforce a minimum password complexity and change of characters when new passwords are created", "weight": 3, "description": "Password complexity requirements enforced via group policy or directory services. Password reuse history configured per organizational policy."},
    "IA.L2-3.5.8": {"family": "Identification and Authentication", "name": "Prohibit password reuse for a specified number of generations", "weight": 3, "description": "Password history enforced in directory services to prevent password reuse. Service accounts use managed rotation where applicable."},
    "IA.L2-3.5.9": {"family": "Identification and Authentication", "name": "Allow temporary password use for system logons with an immediate change to a permanent password", "weight": 1, "description": "New accounts receive one-time temporary passwords and must change at first logon. Help desk resets force change-on-login via GPO or IdP policy."},
    "IA.L2-3.5.10": {"family": "Identification and Authentication", "name": "Store and transmit only cryptographically-protected passwords", "weight": 3, "description": "Directory services store password hashes only (never plaintext). LDAPS/TLS used for authentication traffic; legacy protocols disabled."},
    "IA.L2-3.5.11": {"family": "Identification and Authentication", "name": "Obscure feedback of authentication information", "weight": 1, "description": "Logon screens mask password entry. Error messages do not reveal whether username or password failed. RDP and VPN clients use protected credential prompts."},

    # INCIDENT RESPONSE (IR) - 3 Controls
    "IR.L2-3.6.1": {"family": "Incident Response", "name": "Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities", "weight": 3, "description": "IR plan aligned to NIST SP 800-61. Roles defined for triage, escalation, containment, recovery, and reporting. Tested annually via tabletop exercise."},
    "IR.L2-3.6.2": {"family": "Incident Response", "name": "Track, document, and report incidents to designated officials and/or authorities both internal and external to the organization", "weight": 5, "description": "Incidents logged in ticketing system or SOAR platform. Notifications sent to CISO and legal. Breach reporting to DoW performed per DFARS requirements."},
    "IR.L2-3.6.3": {"family": "Incident Response", "name": "Test the organizational incident response capability", "weight": 3, "description": "Annual incident simulation exercises conducted. Post-exercise lessons learned are captured and used to refine response plans and team readiness."},

    # MAINTENANCE (MA) - 6 Controls
    "MA.L2-3.7.1": {"family": "Maintenance", "name": "Perform maintenance on organizational systems.[26]", "weight": 3, "description": "Maintenance schedules defined via ITIL framework. Systems updated at least once quarterly unless in exception list. Automated patch management applied."},
    "MA.L2-3.7.2": {"family": "Maintenance", "name": "Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance", "weight": 3, "description": "All maintenance performed by vetted IT staff. External maintenance requires contract with cloud CSP or signed NDA. Secure jump host or admin console used."},
    "MA.L2-3.7.3": {"family": "Maintenance", "name": "Ensure equipment removed for off-site maintenance is sanitized of any CUI", "weight": 1, "description": "Data sanitization applied using certified software or degauss tools per NIST SP 800-88 guidelines. Logs retained for audit purposes."},
    "MA.L2-3.7.4": {"family": "Maintenance", "name": "Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems", "weight": 1, "description": "Diagnostic media scanned using updated AV tools or sandboxed analysis prior to use. Use external drives prevented via GPO or endpoint policy."},
    "MA.L2-3.7.5": {"family": "Maintenance", "name": "Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete", "weight": 3, "description": "MFA required for all remote maintenance sessions. Sessions auto-expire upon completion or user logout. Session logging enforced for audit purposes."},
    "MA.L2-3.7.6": {"family": "Maintenance", "name": "Supervise the maintenance activities of maintenance personnel without required access authorization", "weight": 3, "description": "Unapproved personnel escorted or monitored during system access. Access granted only for brief troubleshooting under supervision."},

    # MEDIA PROTECTION (MP) - 9 Controls
    "MP.L2-3.8.1": {"family": "Media Protection", "name": "Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital", "weight": 3, "description": "Physical media stored in locked safes. Digital files encrypted at rest using AES-256. Access tracked via check-in/check-out procedures and monitored by DLP tools."},
    "MP.L2-3.8.2": {"family": "Media Protection", "name": "Limit access to CUI on system media to authorized users", "weight": 3, "description": "Access control lists applied to file shares and system volumes. RBAC and SSO tie access to role and identity context."},
    "MP.L2-3.8.3": {"family": "Media Protection", "name": "Sanitize or destroy system media containing CUI before disposal or release for reuse", "weight": 3, "description": "End-of-life media sanitized using NIST SP 800-88-compliant tools (e.g., DBAN, BitRaser). Physical destruction applied where required for extreme sensitivity."},
    "MP.L2-3.8.4": {"family": "Media Protection", "name": "Mark media with necessary CUI markings and distribution limitations", "weight": 3, "description": "Media labeled with physical tamper-resistant labels indicating “DoW CUI.” Distribution policy enforces “No External Removal Unless CUI Cleared” rule."},
    "MP.L2-3.8.5": {"family": "Media Protection", "name": "Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas", "weight": 3, "description": "Signed transfer receipts and tracking tags used. Encrypted USBs only issued for transfers. Courier services only if fully bonded or DoW-certified."},
    "MP.L2-3.8.6": {"family": "Media Protection", "name": "Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards", "weight": 5, "description": "External drives encrypted using BitLocker-to-Go or VeraCrypt. Public key escrow enables audit controls if lost or stolen."},
    "MP.L2-3.8.7": {"family": "Media Protection", "name": "Control the use of removable media on system components", "weight": 1, "description": "Removable storage restricted via GPO or MDM policy. Authorized USBs tagged with unique serial numbers. Usage reviewed quarterly."},
    "MP.L2-3.8.8": {"family": "Media Protection", "name": "Prohibit the use of portable storage devices when such devices have no identifiable owner", "weight": 1, "description": "All USBs issued from central IT asset pool. Users must check out via IT helpdesk or asset system like ServiceNow."},
    "MP.L2-3.8.9": {"family": "Media Protection", "name": "Protect the confidentiality of backup CUI at storage locations", "weight": 1, "description": "Backups encrypted and transported in tamper-evident containers. Key custodians kept separate from physical transport. Signed chain of custody maintained."},

    # PERSONNEL SECURITY (PS) - 2 Controls
    "PS.L2-3.9.1": {"family": "Personnel Security", "name": "Screen individuals prior to authorizing access to organizational systems containing CUI", "weight": 3, "description": "All access granted only after positive background check or CUI awareness training. Extends to contractors or external vendors processing any manner of sensitive data."},
    "PS.L2-3.9.2": {"family": "Personnel Security", "name": "Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers", "weight": 5, "description": "Account disablements enforced manually or via HR-integrated workflow. Separation interviews ensure transfer or return of system credentials."},

    # PHYSICAL PROTECTION (PE) - 6 Controls
    "PE.L2-3.10.1": {"family": "Physical Protection", "name": "Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals", "weight": 5, "description": "Access controlled via badge readers, biometrics, and 24/7 surveillance. Guards verified at entry for authorized personnel and contracted vendors."},
    "PE.L2-3.10.2": {"family": "Physical Protection", "name": "Protect and monitor the physical facility and support infrastructure for organizational systems", "weight": 5, "description": "Data centers monitored via CCTV, biometrics, and environmental controls. Access limited to Tier-2 IT staff. 24/7 support hubs trigger alerts on unauthorized entry."},
    "PE.L2-3.10.3": {"family": "Physical Protection", "name": "Escort visitors and monitor visitor activity", "weight": 1, "description": "Visitors escorted at all times in secure areas. ID badges issued and scanned on entry. Visits logged via visitor management software or SOAR integration."},
    "PE.L2-3.10.4": {"family": "Physical Protection", "name": "Maintain audit logs of physical access", "weight": 1, "description": "Access control systems log ID, time, date, and access zone. Logs reviewed weekly for suspicious activity or tailgating attempts."},
    "PE.L2-3.10.5": {"family": "Physical Protection", "name": "Control and manage physical access devices", "weight": 1, "description": "Access tokens (badges, fobs) assigned to individuals. Lost/stolen devices revoked immediately and replaced only after physical confirmation of identity."},
    "PE.L2-3.10.6": {"family": "Physical Protection", "name": "Enforce safeguarding measures for CUI at alternate work sites", "weight": 1, "description": "Alternate work site policy requires VPN, encrypted devices, and clean-desk rules. Remote CUI handling reviewed quarterly by the ISO."},

    # RISK ASSESSMENT (RA) - 3 Controls
    "RA.L2-3.11.1": {"family": "Risk Assessment", "name": "Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI", "weight": 3, "description": "Annual third-party FISMA Moderate or High impact assessment conducted. Scoring uses CVSS or NIST risk models. Results published to risk register and auditors."},
    "RA.L2-3.11.2": {"family": "Risk Assessment", "name": "Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified", "weight": 3, "description": "Regular vulnerability scanning applied across servers and cloud workloads using approved scanning tools. Vulnerabilities addressed per organizational remediation SLAs."},
    "RA.L2-3.11.3": {"family": "Risk Assessment", "name": "Remediate vulnerabilities in accordance with risk assessments", "weight": 1, "description": "Vulnerabilities prioritized based on exploit availability and impact. Remediation tracked to closure in risk register and validated quarterly by internal audit."},

    # SECURITY ASSESSMENT (CA) - 4 Controls
    "CA.L2-3.12.1": {"family": "Security Assessment", "name": "Periodically assess the security controls in organizational systems to determine if the controls are effective in their application", "weight": 3, "description": "Third-party penetration testing and control validation performed annually or biannually, based on system tier. Reports aligned with NIST 800-53 or ISO 27001."},
    "CA.L2-3.12.2": {"family": "Security Assessment", "name": "Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems", "weight": 3, "description": "POA&M generated from assessment findings and tracked via GRC system. Milestones linked to budget periods and executive reviews."},
    "CA.L2-3.12.3": {"family": "Security Assessment", "name": "Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls", "weight": 3, "description": "Continuous monitoring performed via SIEM feeds, IDS/IPS, and endpoint telemetry. Semi-annual reviews of effectiveness performed by ISSO or CISO office."},
    "CA.L2-3.12.4": {"family": "Security Assessment", "name": "Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems", "weight": 1, "description": "SSP update triggers include system architecture changes, contract mod, or high-severity findings. Maintained in GRC or SharePoint site with version history tracking."},

    # SYSTEM AND COMMUNICATIONS PROTECTION (SC) - 16 Controls
    "SC.L2-3.13.1": {"family": "System and Communications Protection", "name": "Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems", "weight": 3, "description": "Perimeter and east-west traffic monitored via network IDS/IPS. Internal policies restrict large file transfer or use of unapproved communication methods."},
    "SC.L2-3.13.2": {"family": "System and Communications Protection", "name": "Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems", "weight": 3, "description": "DevSecOps pipeline integrated into CI/CD. Security-by-design principles enforced through threat modeling and code scanning tools (e.g., SonarQube, Checkmarx)."},
    "SC.L2-3.13.3": {"family": "System and Communications Protection", "name": "Separate user functionality from system management functionality", "weight": 3, "description": "Privileged access isolated via jump hosts or dedicated admin workstations. Users cannot access administrative tools or configuration panels directly."},
    "SC.L2-3.13.4": {"family": "System and Communications Protection", "name": "Prevent unauthorized and unintended information transfer via shared system resources", "weight": 1, "description": "Isolation of user tenants in virtualized or SaaS environments. Communications between partitions enforced using security contexts or namespace policies."},
    "SC.L2-3.13.5": {"family": "System and Communications Protection", "name": "Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks", "weight": 3, "description": "Default-deny firewall policies enforced in cloud and on-prem networks. Allow rules reviewed quarterly and removed unless actively used."},
    "SC.L2-3.13.6": {"family": "System and Communications Protection", "name": "Deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception)", "weight": 3, "description": "Unauthenticated traffic to internal endpoints dropped at edge or WAF layer. All services must authenticate through mutual TLS or API gateway certificates."},
    "SC.L2-3.13.7": {"family": "System and Communications Protection", "name": "Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks (i.e., split tunneling)", "weight": 3, "description": "Endpoints unable to dual-hop via split tunneling unless gated by ZTNA. IPSec or tunnel ACLs used to control external network routes."},
    "SC.L2-3.13.8": {"family": "System and Communications Protection", "name": "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards", "weight": 5, "description": "All data in motion over external or untrusted networks protected via TLS 1.3 or IPsec AES-256. Certificates issued from trusted internal or public CA."},
    "SC.L2-3.13.9": {"family": "System and Communications Protection", "name": "Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity", "weight": 3, "description": "Session timeouts administered for HTTP(S), RDP, SSH, and cloud IAM connections. Auto-disconnect enforced via server-side idle timeout policies."},
    "SC.L2-3.13.10": {"family": "System and Communications Protection", "name": "Establish and manage cryptographic keys for cryptography employed in organizational systems", "weight": 3, "description": "Key lifecycle management (generation, rotation, storage, revocation) performed manually or via cloud KMS. Cryptographic keys rotated per organizational policy."},
    "SC.L2-3.13.11": {"family": "System and Communications Protection", "name": "Employ FIPS-validated cryptography when used to protect the confidentiality of CUI", "weight": 1, "description": "FIPS 140-2 validated cryptographic modules used on all endpoints and servers processing or storing CUI. FIPS mode enforced at OS level where available."},
    "SC.L2-3.13.12": {"family": "System and Communications Protection", "name": "Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device.[29]", "weight": 1, "description": "Cameras and microphones on all government-issued devices disabled unless in user-initiated use. Indicators of active state clearly visible to room occupants."},
    "SC.L2-3.13.13": {"family": "System and Communications Protection", "name": "Control and monitor the use of mobile code", "weight": 3, "description": "Browser script execution restricted via CSP headers and group policies. Downloads confined to secure temp directories and auto-scanned by AV."},
    "SC.L2-3.13.14": {"family": "System and Communications Protection", "name": "Control and monitor the use of Voice over Internet Protocol (VoIP) technologies", "weight": 3, "description": "VoIP traffic encrypted in-transit. Use limited to company phones or captive apps tied to Entra ID. Guest-based or unapproved VoIP services blocked."},
    "SC.L2-3.13.15": {"family": "System and Communications Protection", "name": "Protect the authenticity of communications sessions", "weight": 3, "description": "Mutual TLS (mTLS) or certificate pinning used to validate endpoint identity. Session tokens encrypted and stored separately from operational data."},
    "SC.L2-3.13.16": {"family": "System and Communications Protection", "name": "Protect the confidentiality of CUI at rest", "weight": 3, "description": "Disk or volume-level encryption implemented using BitLocker, FileVault, or cloud-native VM disk encryption tools. Encryption keys managed via HSM or secure vault."},

    # SYSTEM AND INFORMATION INTEGRITY (SI) - 7 Controls
    "SI.L2-3.14.1": {"family": "System and Information Integrity", "name": "Identify, report, and correct system flaws in a timely manner", "weight": 3, "description": "Regular vulnerability scans followed by patching or compensating controls within SLA timelines. Flaw remediation prioritized and tracked."},
    "SI.L2-3.14.2": {"family": "System and Information Integrity", "name": "Provide protection from malicious code at designated locations within organizational systems", "weight": 3, "description": "Antimalware agents with realtime protection deployed on endpoints and servers. Definitions updated daily and scan enforcement via Group Policy or MDM."},
    "SI.L2-3.14.3": {"family": "System and Information Integrity", "name": "Monitor system security alerts and advisories and take action in response", "weight": 1, "description": "Security advisories from CISA, vendor notifications, and ISACs are monitored. Response actions include patching, mitigation, and notification to relevant stakeholders per organizational policy."},
    "SI.L2-3.14.4": {"family": "System and Information Integrity", "name": "Update malicious code protection mechanisms when new releases are available", "weight": 3, "description": "Antimalware signatures and definitions updated automatically when new releases are available. Endpoint agents pull latest definitions from vendor cloud or local repository on defined schedule."},
    "SI.L2-3.14.5": {"family": "System and Information Integrity", "name": "Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or executed", "weight": 3, "description": "Antimalware tools (e.g., Defender, Carbon Black) perform real-time file scanning. Weekly or monthly deep scans are logged for compliance."},
    "SI.L2-3.14.6": {"family": "System and Information Integrity", "name": "Monitor organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks", "weight": 3, "description": "Network monitoring via IDS/IPS, SIEM, and endpoint detection tools. Inbound and outbound traffic analyzed for indicators of compromise, malicious code propagation, and unauthorized data exfiltration."},
    "SI.L2-3.14.7": {"family": "System and Information Integrity", "name": "Identify unauthorized use of organizational systems", "weight": 3, "description": "System monitoring detects unauthorized use via IDS/IPS, UEBA, and anomaly detection. Unusual or unauthorized activities related to inbound/outbound communications traffic are identified and escalated to security team."}
}

from annex_weights import apply_annex_weights

apply_annex_weights(CMMC_FRAMEWORK)
