"""Plain-language one-line summaries for all 110 controls (auto-generated)."""

PLAIN_SUMMARIES = {
    "AC.L2-3.1.1": "Set limits so that information system access to authorized users, processes acting on behalf of authorized users, or devices (including o…",
    "AC.L2-3.1.2": "Set limits so that information system access to the types of transactions and functions that authorized users are permitted to execute.",
    "AC.L2-3.1.3": "Control the flow of cui in accordance with approved authorizations.",
    "AC.L2-3.1.4": "Separate the duties of individuals to reduce the risk of malevolent activity without collusion.",
    "AC.L2-3.1.5": "Use the principle of least privilege, including for specific capabilities and organizational systems.",
    "AC.L2-3.1.6": "Use non-privileged accounts or roles when accessing nonsecurity functions, and audit any use of privileged accounts for nonsecurity funct…",
    "AC.L2-3.1.7": "Prevent non-privileged users from executing privileged functions and audit any execution of privileged functions.",
    "AC.L2-3.1.8": "Lock accounts after too many failed login attempts.",
    "AC.L2-3.1.9": "Provide privacy notifications and display system use notifications.",
    "AC.L2-3.1.10": "Use session lock with pattern-hiding displays to prevent access and viewing after a period of inactivity.",
    "AC.L2-3.1.11": "Terminate a network session after a defined condition for session termination.",
    "AC.L2-3.1.12": "Monitor and record and control remote access sessions.",
    "AC.L2-3.1.13": "Use cryptographic mechanisms to protect the confidentiality of remote access transmissions.",
    "AC.L2-3.1.14": "Route remote access via managed access control points.",
    "AC.L2-3.1.15": "Authorize remote execution of privileged commands and remote access to security-relevant information.",
    "AC.L2-3.1.16": "Authorize wireless access prior to allowing such connections.",
    "AC.L2-3.1.17": "Protect wireless access to the system using authentication and encryption.",
    "AC.L2-3.1.18": "Control connection of mobile devices.",
    "AC.L2-3.1.19": "Encrypt CUI on mobile devices and computing platforms.",
    "AC.L2-3.1.20": "Verify and control use of shared system resources.",
    "AC.L2-3.1.21": "Set limits so that use of organizational portable storage devices on external systems.",
    "AC.L2-3.1.22": "Control information posted or processed on publicly accessible systems.",
    "AT.L2-3.2.1": "Make sure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with…",
    "AT.L2-3.2.2": "Make sure that personnel are trained to carry out their assigned information security-related duties and responsibilities.",
    "AT.L2-3.2.3": "Provide training for personnel on recognizing and responding to potential malicious code, social engineering, and other cyber threats.",
    "AU.L2-3.3.1": "Create, retain, and review system audit records to the extent needed to enable the monitoring, analysis, investigation, and reporting of …",
    "AU.L2-3.3.2": "Make sure that organizational systems are uniquely identified and that system audit records contain information to associate logs with sp…",
    "AU.L2-3.3.3": "Review and update system audit records.",
    "AU.L2-3.3.4": "Alert personnel in the event of an audit logging process failure.",
    "AU.L2-3.3.5": "Correlate audit record review, analysis, and reporting processes for investigation and response to indications of inappropriate, suspicio…",
    "AU.L2-3.3.6": "Provide a system capability that compares and synchronizes internal system clocks with an authoritative outside time source.",
    "AU.L2-3.3.7": "Protect audit information and audit tools from unauthorized access, modification, and deletion.",
    "AU.L2-3.3.8": "Set limits so that management of audit logging functionality to a subset of privileged users.",
    "AU.L2-3.3.9": "Report audit findings to organization-defined personnel or roles.",
    "CM.L2-3.4.1": "Establish and maintain baseline configurations and inventories of organizational systems.",
    "CM.L2-3.4.2": "Establish and maintain and enforce security configuration settings for information technology products employed in organizational systems.",
    "CM.L2-3.4.3": "Track, review, approve, and audit changes to organizational systems.",
    "CM.L2-3.4.4": "Analyze the security impacts of changes prior to implementation.",
    "CM.L2-3.4.5": "Define, document, and enforce physical and logical access restrictions associated with changes to organizational systems.",
    "CM.L2-3.4.6": "Use the principle of least functionality by configuring organizational systems to provide only essential capabilities.",
    "CM.L2-3.4.7": "Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services.",
    "CM.L2-3.4.8": "Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or allow-by-exception (whitelisting) policy to …",
    "CM.L2-3.4.9": "Control and monitor user-installed software.",
    "IA.L2-3.5.1": "Identify system users, processes acting on behalf of users, or devices.",
    "IA.L2-3.5.2": "Verify identity before (or verify) the identities of those users, processes, or devices as a prerequisite to allowing access to organizat…",
    "IA.L2-3.5.3": "Require MFA for admin accounts and for remote access by regular users.",
    "IA.L2-3.5.4": "Use identifiers, passwords, or other mechanisms to uniquely identify and authenticate organizational users.",
    "IA.L2-3.5.5": "Prevent reuse of identifiers for a defined period.",
    "IA.L2-3.5.6": "Disable identifiers after a defined period of inactivity.",
    "IA.L2-3.5.7": "Enforce minimum password complexity and change of characters when new passwords are created.",
    "IA.L2-3.5.8": "Block users from reusing recent passwords.",
    "IA.L2-3.5.9": "Temporary passwords must be changed on first login.",
    "IA.L2-3.5.10": "Never store or send passwords in clear text — use hashing and encryption.",
    "IA.L2-3.5.11": "Hide passwords as users type; don't leak hints in error messages.",
    "IR.L2-3.6.1": "Establish and maintain an operational incident-handling capability for organizational systems that includes preparation, detection, analy…",
    "IR.L2-3.6.2": "Track, document, and report incidents to designated officials and authorities both internal and external to the organization.",
    "IR.L2-3.6.3": "Test the organizational incident response capability.",
    "MA.L2-3.7.1": "Perform periodic and timely maintenance on organizational systems.",
    "MA.L2-3.7.2": "Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance.",
    "MA.L2-3.7.3": "Make sure equipment removed for maintenance is sanitized of cui prior to disposal or release for reuse.",
    "MA.L2-3.7.4": "Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems.",
    "MA.L2-3.7.5": "Require multifactor authentication to establish nonlocal maintenance sessions via external networks and terminate such sessions when nonl…",
    "MA.L2-3.7.6": "Supervise the maintenance activities of personnel without required access authorization.",
    "MP.L2-3.8.1": "Protect (i.e., physically and logically) system media containing cui, both digital and non-digital.",
    "MP.L2-3.8.2": "Set limits so that access to cui on system media to authorized users.",
    "MP.L2-3.8.3": "Sanitize or destroy system media containing cui before disposal or release for reuse.",
    "MP.L2-3.8.4": "Mark media with necessary CUI markings and distribution limitations.",
    "MP.L2-3.8.5": "Control access to media containing cui and maintain accountability for media during transport outside of controlled areas.",
    "MP.L2-3.8.6": "Implement cryptographic mechanisms to protect the confidentiality of cui stored on digital media during transport outside of controlled a…",
    "MP.L2-3.8.7": "Control the use of removable media on system components.",
    "MP.L2-3.8.8": "Do not allow the use of portable storage devices when such devices have no identifiable owner.",
    "MP.L2-3.8.9": "Protect the confidentiality of cui backup media during transport outside of controlled areas.",
    "PS.L2-3.9.1": "Screen individuals prior to authorizing access to organizational systems containing CUI.",
    "PS.L2-3.9.2": "Protect organizational systems during and after personnel actions such as terminations and transfers.",
    "PE.L2-3.10.1": "Set limits so that physical access to organizational systems, equipment, and the respective operating environments to authorized individu…",
    "PE.L2-3.10.3": "Escort visitors and monitor visitor activity.",
    "PE.L2-3.10.4": "Maintain audit logs for physical access.",
    "PE.L2-3.10.5": "Control and manage physical access devices.",
    "PE.L2-3.10.2": "Protect and monitor physical plant and support infrastructure.",
    "PE.L2-3.10.6": "Enforce safeguarding measures for CUI at alternate work sites.",
    "RA.L2-3.11.1": "Periodically assess the risk to organizational operations, organizational assets, and individuals resulting from the operation of organiz…",
    "RA.L2-3.11.2": "Scan for vulnerabilities in organizational systems and hosted applications and when new vulnerabilities affecting the systems are identif…",
    "RA.L2-3.11.3": "Remediate vulnerabilities in accordance with risk assessments.",
    "CA.L2-3.12.1": "Periodically assess the security controls in organizational systems to determine if the controls are effective in their application.",
    "CA.L2-3.12.2": "Create and maintain and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizatio…",
    "CA.L2-3.12.3": "Monitor and record security controls on an ongoing basis to ensure the continued effectiveness of the controls.",
    "CA.L2-3.12.4": "Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, and s…",
    "SC.L2-3.13.1": "Monitor, control, and protect organizational communications at the external boundaries and key internal boundaries of organizational syst…",
    "SC.L2-3.13.2": "Use architectural designs, software development techniques, and systems engineering principles that promote effective information security.",
    "SC.L2-3.13.3": "Separate user functionality from system management functionality.",
    "SC.L2-3.13.4": "Prevent unauthorized and unintended information transfer via shared system resources.",
    "SC.L2-3.13.5": "Deny network communications traffic by default and allow network communications traffic by exception.",
    "SC.L2-3.13.6": "Prevent unauthenticated sessions from establishing communications with internal systems.",
    "SC.L2-3.13.7": "Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and connecting with external n…",
    "SC.L2-3.13.8": "Encrypt CUI when it moves across networks.",
    "SC.L2-3.13.9": "Terminate network connections associated with communications sessions at the end of the sessions.",
    "SC.L2-3.13.10": "Establish and maintain and manage cryptographic keys for cryptography employed in organizational systems.",
    "SC.L2-3.13.11": "Use FIPS-validated encryption wherever CUI is protected.",
    "SC.L2-3.13.12": "Do not allow remote activation of collaborative computing devices and provide explicit indication of use.",
    "SC.L2-3.13.13": "Control and monitor the use of mobile code.",
    "SC.L2-3.13.14": "Control and monitor the use of voice over internet protocol (voip) technologies.",
    "SC.L2-3.13.15": "Protect the authenticity of communications sessions.",
    "SC.L2-3.13.16": "Protect the confidentiality of cui at rest.",
    "SI.L2-3.14.1": "Identify, report, and correct system flaws in a timely manner.",
    "SI.L2-3.14.2": "Provide protection from malicious code at designated locations within organizational systems.",
    "SI.L2-3.14.3": "Monitor and record organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of pot…",
    "SI.L2-3.14.4": "Identify unauthorized use of organizational systems.",
    "SI.L2-3.14.5": "Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or e…",
    "SI.L2-3.14.6": "Monitor and record system wordings, software, and hardware configurations for unauthorized changes.",
    "SI.L2-3.14.7": "Verify the correct operation of security functions.",
}
