CONTROLS_CATALOG: list[dict] = [
    # ═══════════════════════════════════════════════════════════════
    # CMMC Rev 2 - Level 1 (FCI / 15 practices, 48 CFR 52.204-21)
    # ═══════════════════════════════════════════════════════════════
    # Access Control (AC)
    {"id": "AC.L1-b.1.i", "title": "Limit information system access to authorized users, processes acting on behalf of authorized users, or devices (including other information systems).", "framework": "CMMC Rev 2", "clause": "AC.L1-b.1.i", "level": 1},
    {"id": "AC.L1-b.1.ii", "title": "Limit information system access to the types of transactions and functions that authorized users are permitted to execute.", "framework": "CMMC Rev 2", "clause": "AC.L1-b.1.ii", "level": 1},
    {"id": "AC.L1-b.1.iii", "title": "Verify and control/limit connections to and use of external information systems.", "framework": "CMMC Rev 2", "clause": "AC.L1-b.1.iii", "level": 1},
    {"id": "AC.L1-b.1.iv", "title": "Control information posted or processed on publicly accessible information systems.", "framework": "CMMC Rev 2", "clause": "AC.L1-b.1.iv", "level": 1},
    # Identification and Authentication (IA)
    {"id": "IA.L1-b.1.v", "title": "Identify information system users, processes acting on behalf of users, or devices.", "framework": "CMMC Rev 2", "clause": "IA.L1-b.1.v", "level": 1},
    {"id": "IA.L1-b.1.vi", "title": "Authenticate (or verify) the identities of those users, processes, or devices, as a prerequisite to allowing access to organizational information systems.", "framework": "CMMC Rev 2", "clause": "IA.L1-b.1.vi", "level": 1},
    # Media Protection (MP)
    {"id": "MP.L1-b.1.vii", "title": "Sanitize or destroy information system media containing Federal Contract Information before disposal or release for reuse.", "framework": "CMMC Rev 2", "clause": "MP.L1-b.1.vii", "level": 1},
    # Physical Protection (PE)
    {"id": "PE.L1-b.1.viii", "title": "Limit physical access to organizational information systems, equipment, and the respective operating environments to authorized individuals.", "framework": "CMMC Rev 2", "clause": "PE.L1-b.1.viii", "level": 1},
    {"id": "PE.L1-b.1.ix", "title": "Escort visitors and monitor visitor activity; maintain audit logs of physical access; and control and manage physical access devices.", "framework": "CMMC Rev 2", "clause": "PE.L1-b.1.ix", "level": 1},
    # System and Communications Protection (SC)
    {"id": "SC.L1-b.1.x", "title": "Monitor, control, and protect organizational communications (i.e., information transmitted or received by organizational information systems) at the external boundaries and key internal boundaries of the information systems.", "framework": "CMMC Rev 2", "clause": "SC.L1-b.1.x", "level": 1},
    {"id": "SC.L1-b.1.xi", "title": "Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.", "framework": "CMMC Rev 2", "clause": "SC.L1-b.1.xi", "level": 1},
    # System and Information Integrity (SI)
    {"id": "SI.L1-b.1.xii", "title": "Identify, report, and correct information and information system flaws in a timely manner.", "framework": "CMMC Rev 2", "clause": "SI.L1-b.1.xii", "level": 1},
    {"id": "SI.L1-b.1.xiii", "title": "Provide protection from malicious code at appropriate locations within organizational information systems.", "framework": "CMMC Rev 2", "clause": "SI.L1-b.1.xiii", "level": 1},
    {"id": "SI.L1-b.1.xiv", "title": "Update malicious code protection mechanisms when new releases are available.", "framework": "CMMC Rev 2", "clause": "SI.L1-b.1.xiv", "level": 1},
    {"id": "SI.L1-b.1.xv", "title": "Perform periodic scans of the information system and real-time scans of files from external sources as files are downloaded, opened, or executed.", "framework": "CMMC Rev 2", "clause": "SI.L1-b.1.xv", "level": 1},
    # ═══════════════════════════════════════════════════════════════
    # CMMC Rev 2 - Level 2 (CUI / 110 practices, NIST SP 800-171 Rev 2)
    # ═══════════════════════════════════════════════════════════════
    # Access Control (AC)
    {"id": "AC.L2-3.1.1", "title": "Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems)", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.1", "level": 2},
    {"id": "AC.L2-3.1.2", "title": "Limit system access to the types of transactions and functions that authorized users are permitted to execute", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.2", "level": 2},
    {"id": "AC.L2-3.1.3", "title": "Control the flow of CUI in accordance with approved authorizations", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.3", "level": 2},
    {"id": "AC.L2-3.1.4", "title": "Separate the duties of individuals to reduce the risk of malevolent activity without collusion", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.4", "level": 2},
    {"id": "AC.L2-3.1.5", "title": "Employ the principle of least privilege, including for specific security functions and privileged accounts", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.5", "level": 2},
    {"id": "AC.L2-3.1.6", "title": "Use non-privileged accounts or roles when accessing nonsecurity functions", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.6", "level": 2},
    {"id": "AC.L2-3.1.7", "title": "Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.7", "level": 2},
    {"id": "AC.L2-3.1.8", "title": "Limit unsuccessful logon attempts", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.8", "level": 2},
    {"id": "AC.L2-3.1.9", "title": "Provide privacy and security notices consistent with applicable CUI rules", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.9", "level": 2},
    {"id": "AC.L2-3.1.10", "title": "Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.10", "level": 2},
    {"id": "AC.L2-3.1.11", "title": "Terminate (automatically) a user session after a defined condition", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.11", "level": 2},
    {"id": "AC.L2-3.1.12", "title": "Monitor and control remote access sessions", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.12", "level": 2},
    {"id": "AC.L2-3.1.13", "title": "Employ cryptographic mechanisms to protect the confidentiality of remote access sessions", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.13", "level": 2},
    {"id": "AC.L2-3.1.14", "title": "Route remote access via managed access control points", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.14", "level": 2},
    {"id": "AC.L2-3.1.15", "title": "Authorize remote execution of privileged commands and remote access to security-relevant information", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.15", "level": 2},
    {"id": "AC.L2-3.1.16", "title": "Authorize wireless access prior to allowing such connections", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.16", "level": 2},
    {"id": "AC.L2-3.1.17", "title": "Protect wireless access using authentication and encryption", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.17", "level": 2},
    {"id": "AC.L2-3.1.18", "title": "Control connection of mobile devices", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.18", "level": 2},
    {"id": "AC.L2-3.1.19", "title": "Encrypt CUI on mobile devices and mobile computing platforms", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.19", "level": 2},
    {"id": "AC.L2-3.1.20", "title": "Verify and control/limit connections to and use of external systems", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.20", "level": 2},
    {"id": "AC.L2-3.1.21", "title": "Limit use of portable storage devices on external systems", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.21", "level": 2},
    {"id": "AC.L2-3.1.22", "title": "Control CUI posted or processed on publicly accessible systems", "framework": "CMMC Rev 2", "clause": "AC.L2-3.1.22", "level": 2},
    # Awareness and Training (AT)
    {"id": "AT.L2-3.2.1", "title": "Ensure that managers, systems administrators, and users of organizational systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems", "framework": "CMMC Rev 2", "clause": "AT.L2-3.2.1", "level": 2},
    {"id": "AT.L2-3.2.2", "title": "Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities", "framework": "CMMC Rev 2", "clause": "AT.L2-3.2.2", "level": 2},
    {"id": "AT.L2-3.2.3", "title": "Provide security awareness training on recognizing and reporting potential indicators of insider threat", "framework": "CMMC Rev 2", "clause": "AT.L2-3.2.3", "level": 2},
    # Audit and Accountability (AU)
    {"id": "AU.L2-3.3.1", "title": "Create and retain system audit logs and records to the extent needed to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity", "framework": "CMMC Rev 2", "clause": "AU.L2-3.3.1", "level": 2},
    {"id": "AU.L2-3.3.2", "title": "Ensure that the actions of individual system users can be uniquely traced to those users, so they can be held accountable for their actions", "framework": "CMMC Rev 2", "clause": "AU.L2-3.3.2", "level": 2},
    {"id": "AU.L2-3.3.3", "title": "Review and update logged events", "framework": "CMMC Rev 2", "clause": "AU.L2-3.3.3", "level": 2},
    {"id": "AU.L2-3.3.4", "title": "Alert in the event of an audit logging process failure", "framework": "CMMC Rev 2", "clause": "AU.L2-3.3.4", "level": 2},
    {"id": "AU.L2-3.3.5", "title": "Correlate audit record review, analysis, and reporting processes for investigation and response to indications of unlawful, unauthorized, suspicious, or unusual activity", "framework": "CMMC Rev 2", "clause": "AU.L2-3.3.5", "level": 2},
    {"id": "AU.L2-3.3.6", "title": "Provide audit record reduction and report generation to support on-demand analysis and reporting", "framework": "CMMC Rev 2", "clause": "AU.L2-3.3.6", "level": 2},
    {"id": "AU.L2-3.3.7", "title": "Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records", "framework": "CMMC Rev 2", "clause": "AU.L2-3.3.7", "level": 2},
    {"id": "AU.L2-3.3.8", "title": "Protect audit information and audit logging tools from unauthorized access, modification, and deletion", "framework": "CMMC Rev 2", "clause": "AU.L2-3.3.8", "level": 2},
    {"id": "AU.L2-3.3.9", "title": "Limit management of audit logging functionality to a subset of privileged users", "framework": "CMMC Rev 2", "clause": "AU.L2-3.3.9", "level": 2},
    # Configuration Management (CM)
    {"id": "CM.L2-3.4.1", "title": "Establish and maintain baseline configurations and inventories of organizational systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles", "framework": "CMMC Rev 2", "clause": "CM.L2-3.4.1", "level": 2},
    {"id": "CM.L2-3.4.2", "title": "Establish and enforce security configuration settings for information technology products employed in organizational systems", "framework": "CMMC Rev 2", "clause": "CM.L2-3.4.2", "level": 2},
    {"id": "CM.L2-3.4.3", "title": "Track, review, approve or disapprove, and log changes to organizational systems", "framework": "CMMC Rev 2", "clause": "CM.L2-3.4.3", "level": 2},
    {"id": "CM.L2-3.4.4", "title": "Analyze the security impact of changes prior to implementation", "framework": "CMMC Rev 2", "clause": "CM.L2-3.4.4", "level": 2},
    {"id": "CM.L2-3.4.5", "title": "Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems", "framework": "CMMC Rev 2", "clause": "CM.L2-3.4.5", "level": 2},
    {"id": "CM.L2-3.4.6", "title": "Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities", "framework": "CMMC Rev 2", "clause": "CM.L2-3.4.6", "level": 2},
    {"id": "CM.L2-3.4.7", "title": "Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services", "framework": "CMMC Rev 2", "clause": "CM.L2-3.4.7", "level": 2},
    {"id": "CM.L2-3.4.8", "title": "Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software", "framework": "CMMC Rev 2", "clause": "CM.L2-3.4.8", "level": 2},
    {"id": "CM.L2-3.4.9", "title": "Control and monitor user-installed software", "framework": "CMMC Rev 2", "clause": "CM.L2-3.4.9", "level": 2},
    # Identification and Authentication (IA)
    {"id": "IA.L2-3.5.1", "title": "Identify system users, processes acting on behalf of users, and devices", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.1", "level": 2},
    {"id": "IA.L2-3.5.2", "title": "Authenticate (or verify) the identities of users, processes, or devices, as a prerequisite to allowing access to organizational systems", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.2", "level": 2},
    {"id": "IA.L2-3.5.3", "title": "Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.[24] [25]", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.3", "level": 2},
    {"id": "IA.L2-3.5.4", "title": "Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.4", "level": 2},
    {"id": "IA.L2-3.5.5", "title": "Prevent reuse of identifiers for a defined period", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.5", "level": 2},
    {"id": "IA.L2-3.5.6", "title": "Disable identifiers after a defined period of inactivity", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.6", "level": 2},
    {"id": "IA.L2-3.5.7", "title": "Enforce a minimum password complexity and change of characters when new passwords are created", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.7", "level": 2},
    {"id": "IA.L2-3.5.8", "title": "Prohibit password reuse for a specified number of generations", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.8", "level": 2},
    {"id": "IA.L2-3.5.9", "title": "Allow temporary password use for system logons with an immediate change to a permanent password", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.9", "level": 2},
    {"id": "IA.L2-3.5.10", "title": "Store and transmit only cryptographically-protected passwords", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.10", "level": 2},
    {"id": "IA.L2-3.5.11", "title": "Obscure feedback of authentication information", "framework": "CMMC Rev 2", "clause": "IA.L2-3.5.11", "level": 2},
    # Incident Response (IR)
    {"id": "IR.L2-3.6.1", "title": "Establish an operational incident-handling capability for organizational systems that includes preparation, detection, analysis, containment, recovery, and user response activities", "framework": "CMMC Rev 2", "clause": "IR.L2-3.6.1", "level": 2},
    {"id": "IR.L2-3.6.2", "title": "Track, document, and report incidents to designated officials and/or authorities both internal and external to the organization", "framework": "CMMC Rev 2", "clause": "IR.L2-3.6.2", "level": 2},
    {"id": "IR.L2-3.6.3", "title": "Test the organizational incident response capability", "framework": "CMMC Rev 2", "clause": "IR.L2-3.6.3", "level": 2},
    # Maintenance (MA)
    {"id": "MA.L2-3.7.1", "title": "Perform maintenance on organizational systems.[26]", "framework": "CMMC Rev 2", "clause": "MA.L2-3.7.1", "level": 2},
    {"id": "MA.L2-3.7.2", "title": "Provide controls on the tools, techniques, mechanisms, and personnel used to conduct system maintenance", "framework": "CMMC Rev 2", "clause": "MA.L2-3.7.2", "level": 2},
    {"id": "MA.L2-3.7.3", "title": "Ensure equipment removed for off-site maintenance is sanitized of any CUI", "framework": "CMMC Rev 2", "clause": "MA.L2-3.7.3", "level": 2},
    {"id": "MA.L2-3.7.4", "title": "Check media containing diagnostic and test programs for malicious code before the media are used in organizational systems", "framework": "CMMC Rev 2", "clause": "MA.L2-3.7.4", "level": 2},
    {"id": "MA.L2-3.7.5", "title": "Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete", "framework": "CMMC Rev 2", "clause": "MA.L2-3.7.5", "level": 2},
    {"id": "MA.L2-3.7.6", "title": "Supervise the maintenance activities of maintenance personnel without required access authorization", "framework": "CMMC Rev 2", "clause": "MA.L2-3.7.6", "level": 2},
    # Media Protection (MP)
    {"id": "MP.L2-3.8.1", "title": "Protect (i.e., physically control and securely store) system media containing CUI, both paper and digital", "framework": "CMMC Rev 2", "clause": "MP.L2-3.8.1", "level": 2},
    {"id": "MP.L2-3.8.2", "title": "Limit access to CUI on system media to authorized users", "framework": "CMMC Rev 2", "clause": "MP.L2-3.8.2", "level": 2},
    {"id": "MP.L2-3.8.3", "title": "Sanitize or destroy system media containing CUI before disposal or release for reuse", "framework": "CMMC Rev 2", "clause": "MP.L2-3.8.3", "level": 2},
    {"id": "MP.L2-3.8.4", "title": "Mark media with necessary CUI markings and distribution limitations", "framework": "CMMC Rev 2", "clause": "MP.L2-3.8.4", "level": 2},
    {"id": "MP.L2-3.8.5", "title": "Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas", "framework": "CMMC Rev 2", "clause": "MP.L2-3.8.5", "level": 2},
    {"id": "MP.L2-3.8.6", "title": "Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards", "framework": "CMMC Rev 2", "clause": "MP.L2-3.8.6", "level": 2},
    {"id": "MP.L2-3.8.7", "title": "Control the use of removable media on system components", "framework": "CMMC Rev 2", "clause": "MP.L2-3.8.7", "level": 2},
    {"id": "MP.L2-3.8.8", "title": "Prohibit the use of portable storage devices when such devices have no identifiable owner", "framework": "CMMC Rev 2", "clause": "MP.L2-3.8.8", "level": 2},
    {"id": "MP.L2-3.8.9", "title": "Protect the confidentiality of backup CUI at storage locations", "framework": "CMMC Rev 2", "clause": "MP.L2-3.8.9", "level": 2},
    # Personnel Security (PS)
    {"id": "PS.L2-3.9.1", "title": "Screen individuals prior to authorizing access to organizational systems containing CUI", "framework": "CMMC Rev 2", "clause": "PS.L2-3.9.1", "level": 2},
    {"id": "PS.L2-3.9.2", "title": "Ensure that organizational systems containing CUI are protected during and after personnel actions such as terminations and transfers", "framework": "CMMC Rev 2", "clause": "PS.L2-3.9.2", "level": 2},
    # Physical Protection (PE)
    {"id": "PE.L2-3.10.1", "title": "Limit physical access to organizational systems, equipment, and the respective operating environments to authorized individuals", "framework": "CMMC Rev 2", "clause": "PE.L2-3.10.1", "level": 2},
    {"id": "PE.L2-3.10.2", "title": "Protect and monitor the physical facility and support infrastructure for organizational systems", "framework": "CMMC Rev 2", "clause": "PE.L2-3.10.2", "level": 2},
    {"id": "PE.L2-3.10.3", "title": "Escort visitors and monitor visitor activity", "framework": "CMMC Rev 2", "clause": "PE.L2-3.10.3", "level": 2},
    {"id": "PE.L2-3.10.4", "title": "Maintain audit logs of physical access", "framework": "CMMC Rev 2", "clause": "PE.L2-3.10.4", "level": 2},
    {"id": "PE.L2-3.10.5", "title": "Control and manage physical access devices", "framework": "CMMC Rev 2", "clause": "PE.L2-3.10.5", "level": 2},
    {"id": "PE.L2-3.10.6", "title": "Enforce safeguarding measures for CUI at alternate work sites", "framework": "CMMC Rev 2", "clause": "PE.L2-3.10.6", "level": 2},
    # Risk Assessment (RA)
    {"id": "RA.L2-3.11.1", "title": "Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational systems and the associated processing, storage, or transmission of CUI", "framework": "CMMC Rev 2", "clause": "RA.L2-3.11.1", "level": 2},
    {"id": "RA.L2-3.11.2", "title": "Scan for vulnerabilities in organizational systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified", "framework": "CMMC Rev 2", "clause": "RA.L2-3.11.2", "level": 2},
    {"id": "RA.L2-3.11.3", "title": "Remediate vulnerabilities in accordance with risk assessments", "framework": "CMMC Rev 2", "clause": "RA.L2-3.11.3", "level": 2},
    # Security Assessment (CA)
    {"id": "CA.L2-3.12.1", "title": "Periodically assess the security controls in organizational systems to determine if the controls are effective in their application", "framework": "CMMC Rev 2", "clause": "CA.L2-3.12.1", "level": 2},
    {"id": "CA.L2-3.12.2", "title": "Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational systems", "framework": "CMMC Rev 2", "clause": "CA.L2-3.12.2", "level": 2},
    {"id": "CA.L2-3.12.3", "title": "Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls", "framework": "CMMC Rev 2", "clause": "CA.L2-3.12.3", "level": 2},
    {"id": "CA.L2-3.12.4", "title": "Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems", "framework": "CMMC Rev 2", "clause": "CA.L2-3.12.4", "level": 2},
    # System and Communications Protection (SC)
    {"id": "SC.L2-3.13.1", "title": "Monitor, control, and protect communications (i.e., information transmitted or received by organizational systems) at the external boundaries and key internal boundaries of organizational systems", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.1", "level": 2},
    {"id": "SC.L2-3.13.2", "title": "Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational systems", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.2", "level": 2},
    {"id": "SC.L2-3.13.3", "title": "Separate user functionality from system management functionality", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.3", "level": 2},
    {"id": "SC.L2-3.13.4", "title": "Prevent unauthorized and unintended information transfer via shared system resources", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.4", "level": 2},
    {"id": "SC.L2-3.13.5", "title": "Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.5", "level": 2},
    {"id": "SC.L2-3.13.6", "title": "Deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception)", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.6", "level": 2},
    {"id": "SC.L2-3.13.7", "title": "Prevent remote devices from simultaneously establishing non-remote connections with organizational systems and communicating via some other connection to resources in external networks (i.e., split tunneling)", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.7", "level": 2},
    {"id": "SC.L2-3.13.8", "title": "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.8", "level": 2},
    {"id": "SC.L2-3.13.9", "title": "Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.9", "level": 2},
    {"id": "SC.L2-3.13.10", "title": "Establish and manage cryptographic keys for cryptography employed in organizational systems", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.10", "level": 2},
    {"id": "SC.L2-3.13.11", "title": "Employ FIPS-validated cryptography when used to protect the confidentiality of CUI", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.11", "level": 2},
    {"id": "SC.L2-3.13.12", "title": "Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device.[29]", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.12", "level": 2},
    {"id": "SC.L2-3.13.13", "title": "Control and monitor the use of mobile code", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.13", "level": 2},
    {"id": "SC.L2-3.13.14", "title": "Control and monitor the use of Voice over Internet Protocol (VoIP) technologies", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.14", "level": 2},
    {"id": "SC.L2-3.13.15", "title": "Protect the authenticity of communications sessions", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.15", "level": 2},
    {"id": "SC.L2-3.13.16", "title": "Protect the confidentiality of CUI at rest", "framework": "CMMC Rev 2", "clause": "SC.L2-3.13.16", "level": 2},
    # System and Information Integrity (SI)
    {"id": "SI.L2-3.14.1", "title": "Identify, report, and correct system flaws in a timely manner", "framework": "CMMC Rev 2", "clause": "SI.L2-3.14.1", "level": 2},
    {"id": "SI.L2-3.14.2", "title": "Provide protection from malicious code at designated locations within organizational systems", "framework": "CMMC Rev 2", "clause": "SI.L2-3.14.2", "level": 2},
    {"id": "SI.L2-3.14.3", "title": "Monitor system security alerts and advisories and take action in response", "framework": "CMMC Rev 2", "clause": "SI.L2-3.14.3", "level": 2},
    {"id": "SI.L2-3.14.4", "title": "Update malicious code protection mechanisms when new releases are available", "framework": "CMMC Rev 2", "clause": "SI.L2-3.14.4", "level": 2},
    {"id": "SI.L2-3.14.5", "title": "Perform periodic scans of organizational systems and real-time scans of files from external sources as files are downloaded, opened, or executed", "framework": "CMMC Rev 2", "clause": "SI.L2-3.14.5", "level": 2},
    {"id": "SI.L2-3.14.6", "title": "Monitor organizational systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks", "framework": "CMMC Rev 2", "clause": "SI.L2-3.14.6", "level": 2},
    {"id": "SI.L2-3.14.7", "title": "Identify unauthorized use of organizational systems", "framework": "CMMC Rev 2", "clause": "SI.L2-3.14.7", "level": 2},
    # ═══════════════════════════════════════════════════════════════
    # CMMC Rev 2 - Level 3 (Critical CUI / 24 practices, NIST SP 800-172)
    # ═══════════════════════════════════════════════════════════════
    # Access Control (AC)
    {"id": "AC.L3-3.1.2e", "title": "Restrict access to systems and system components to only those information resources that are owned, provisioned, or issued by the organization.", "framework": "CMMC Rev 2", "clause": "AC.L3-3.1.2e", "level": 3},
    {"id": "AC.L3-3.1.3e", "title": "Employ secure information transfer solutions to control information flows between security domains on connected systems.", "framework": "CMMC Rev 2", "clause": "AC.L3-3.1.3e", "level": 3},
    # Awareness and Training (AT)
    {"id": "AT.L3-3.2.1e", "title": "Provide awareness training upon initial hire, following a significant cyber event, and at least annually, focused on recognizing and responding to threats from social engineering, advanced persistent threat actors, breaches, and suspicious behaviors; update the training at least annually or when there are significant changes to the threat.", "framework": "CMMC Rev 2", "clause": "AT.L3-3.2.1e", "level": 3},
    {"id": "AT.L3-3.2.2e", "title": "Include practical exercises in awareness training for all users, tailored by roles, to include general users, users with specialized roles, and privileged users, that are aligned with current threat scenarios and provide feedback to individuals involved in the training and their supervisors.", "framework": "CMMC Rev 2", "clause": "AT.L3-3.2.2e", "level": 3},
    # Configuration Management (CM)
    {"id": "CM.L3-3.4.1e", "title": "Establish and maintain an authoritative source and repository to provide a trusted source and accountability for approved and implemented system components.", "framework": "CMMC Rev 2", "clause": "CM.L3-3.4.1e", "level": 3},
    {"id": "CM.L3-3.4.2e", "title": "Employ automated mechanisms to detect misconfigured or unauthorized system components; after detection, remove the components or place the components in a quarantine or remediation network to facilitate patching, re-configuration, or other mitigations.", "framework": "CMMC Rev 2", "clause": "CM.L3-3.4.2e", "level": 3},
    {"id": "CM.L3-3.4.3e", "title": "Employ automated discovery and management tools to maintain an up-to-date, complete, accurate, and readily available inventory of system components.", "framework": "CMMC Rev 2", "clause": "CM.L3-3.4.3e", "level": 3},
    # Identification and Authentication (IA)
    {"id": "IA.L3-3.5.1e", "title": "Identify and authenticate systems and system components, where possible, before establishing a network connection using bidirectional authentication that is cryptographically based and replay resistant.", "framework": "CMMC Rev 2", "clause": "IA.L3-3.5.1e", "level": 3},
    {"id": "IA.L3-3.5.3e", "title": "Employ automated or manual/procedural mechanisms to prohibit system components from connecting to organizational systems unless the components are known, authenticated, in a properly configured state, or in a trust profile.", "framework": "CMMC Rev 2", "clause": "IA.L3-3.5.3e", "level": 3},
    # Incident Response (IR)
    {"id": "IR.L3-3.6.1e", "title": "Establish and maintain a security operations center capability that operates 24/7, with allowance for remote/on-call staff.", "framework": "CMMC Rev 2", "clause": "IR.L3-3.6.1e", "level": 3},
    {"id": "IR.L3-3.6.2e", "title": "Establish and maintain a cyber incident response team that can be deployed by the organization within 24 hours.", "framework": "CMMC Rev 2", "clause": "IR.L3-3.6.2e", "level": 3},
    # Personnel Security (PS)
    {"id": "PS.L3-3.9.2e", "title": "Protect organizational systems when adverse information develops or is obtained about individuals with access to CUI.", "framework": "CMMC Rev 2", "clause": "PS.L3-3.9.2e", "level": 3},
    # Risk Assessment (RA)
    {"id": "RA.L3-3.11.1e", "title": "Employ threat intelligence, at a minimum from open or commercial sources, and any DoD-provided sources, as part of a risk assessment to guide and inform the development of organizational systems, security architectures, selection of security solutions, monitoring, threat hunting, and response and recovery activities.", "framework": "CMMC Rev 2", "clause": "RA.L3-3.11.1e", "level": 3},
    {"id": "RA.L3-3.11.2e", "title": "Conduct cyber threat hunting activities on an on-going aperiodic basis or when indications warrant, to search for indicators of compromise in organizational systems and detect, track, and disrupt threats that evade existing controls.", "framework": "CMMC Rev 2", "clause": "RA.L3-3.11.2e", "level": 3},
    {"id": "RA.L3-3.11.3e", "title": "Employ advanced automation and analytics capabilities in support of analysts to predict and identify risks to organizations, systems, and system components.", "framework": "CMMC Rev 2", "clause": "RA.L3-3.11.3e", "level": 3},
    {"id": "RA.L3-3.11.4e", "title": "Document or reference in the system security plan the security solution selected, the rationale for the security solution, and the risk determination.", "framework": "CMMC Rev 2", "clause": "RA.L3-3.11.4e", "level": 3},
    {"id": "RA.L3-3.11.5e", "title": "Assess the effectiveness of security solutions at least annually or upon receipt of relevant cyber threat information, or in response to a relevant cyber incident, to address anticipated risk to organizational systems and the organization based on current and accumulated threat intelligence.", "framework": "CMMC Rev 2", "clause": "RA.L3-3.11.5e", "level": 3},
    {"id": "RA.L3-3.11.6e", "title": "Assess, respond to, and monitor supply chain risks associated with organizational systems and system components.", "framework": "CMMC Rev 2", "clause": "RA.L3-3.11.6e", "level": 3},
    {"id": "RA.L3-3.11.7e", "title": "Develop a plan for managing supply chain risks associated with organizational systems and system components; update the plan at least annually, and upon receipt of relevant cyber threat information, or in response to a relevant cyber incident.", "framework": "CMMC Rev 2", "clause": "RA.L3-3.11.7e", "level": 3},
    # Security Assessment (CA)
    {"id": "CA.L3-3.12.1e", "title": "Conduct penetration testing at least annually or when significant security changes are made to the system, leveraging automated scanning tools and ad hoc tests using subject matter experts.", "framework": "CMMC Rev 2", "clause": "CA.L3-3.12.1e", "level": 3},
    # System and Communications Protection (SC)
    {"id": "SC.L3-3.13.4e", "title": "Employ physical isolation techniques or logical isolation techniques or both in organizational systems and system components.", "framework": "CMMC Rev 2", "clause": "SC.L3-3.13.4e", "level": 3},
    # System and Information Integrity (SI)
    {"id": "SI.L3-3.14.1e", "title": "Verify the integrity of security critical and essential software using root of trust mechanisms or cryptographic signatures.", "framework": "CMMC Rev 2", "clause": "SI.L3-3.14.1e", "level": 3},
    {"id": "SI.L3-3.14.3e", "title": "Include specialized assets such as IoT, IIoT, OT, GFE, Restricted Information Systems and test equipment in the scope of the specified enhanced security requirements or are segregated in purpose-specific networks.", "framework": "CMMC Rev 2", "clause": "SI.L3-3.14.3e", "level": 3},
    {"id": "SI.L3-3.14.6e", "title": "Use threat indicator information and effective mitigations obtained from, at a minimum, open or commercial sources, and any DoD-provided sources, to guide and inform intrusion detection and threat hunting.", "framework": "CMMC Rev 2", "clause": "SI.L3-3.14.6e", "level": 3},

    # SOC 2 — Trust Services Criteria
    # ═══════════════════════════════════════════════════════════════
    {"id": "CC1.1", "title": "Integrity and Ethical Values", "framework": "SOC 2", "clause": "CC1.1", "level": None},
    {"id": "CC1.2", "title": "Board Independence and Oversight", "framework": "SOC 2", "clause": "CC1.2", "level": None},
    {"id": "CC1.3", "title": "Organizational Structure", "framework": "SOC 2", "clause": "CC1.3", "level": None},
    {"id": "CC1.4", "title": "Commitment to Competence", "framework": "SOC 2", "clause": "CC1.4", "level": None},
    {"id": "CC1.5", "title": "Accountability", "framework": "SOC 2", "clause": "CC1.5", "level": None},
    {"id": "CC2.1", "title": "Use Relevant Information", "framework": "SOC 2", "clause": "CC2.1", "level": None},
    {"id": "CC2.2", "title": "Internal Communication", "framework": "SOC 2", "clause": "CC2.2", "level": None},
    {"id": "CC2.3", "title": "External Communication", "framework": "SOC 2", "clause": "CC2.3", "level": None},
    {"id": "CC3.1", "title": "Specified Objectives", "framework": "SOC 2", "clause": "CC3.1", "level": None},
    {"id": "CC3.2", "title": "Risk Identification", "framework": "SOC 2", "clause": "CC3.2", "level": None},
    {"id": "CC3.3", "title": "Fraud Consideration", "framework": "SOC 2", "clause": "CC3.3", "level": None},
    {"id": "CC3.4", "title": "Change Identification", "framework": "SOC 2", "clause": "CC3.4", "level": None},
    {"id": "CC4.1", "title": "Ongoing Monitoring", "framework": "SOC 2", "clause": "CC4.1", "level": None},
    {"id": "CC4.2", "title": "Deficiency Communication", "framework": "SOC 2", "clause": "CC4.2", "level": None},
    {"id": "CC5.1", "title": "Risk Mitigation Selection", "framework": "SOC 2", "clause": "CC5.1", "level": None},
    {"id": "CC5.2", "title": "Technology Controls", "framework": "SOC 2", "clause": "CC5.2", "level": None},
    {"id": "CC5.3", "title": "Policy Deployment", "framework": "SOC 2", "clause": "CC5.3", "level": None},
    {"id": "CC6.1", "title": "Logical Access Security", "framework": "SOC 2", "clause": "CC6.1", "level": None},
    {"id": "CC6.2", "title": "User Access Provisioning", "framework": "SOC 2", "clause": "CC6.2", "level": None},
    {"id": "CC6.3", "title": "Privileged Access Management", "framework": "SOC 2", "clause": "CC6.3", "level": None},
    {"id": "CC6.4", "title": "Physical Access Restrictions", "framework": "SOC 2", "clause": "CC6.4", "level": None},
    {"id": "CC6.5", "title": "Asset Decommissioning", "framework": "SOC 2", "clause": "CC6.5", "level": None},
    {"id": "CC6.6", "title": "External Threats", "framework": "SOC 2", "clause": "CC6.6", "level": None},
    {"id": "CC6.7", "title": "Data Transmission", "framework": "SOC 2", "clause": "CC6.7", "level": None},
    {"id": "CC6.8", "title": "Malware Prevention", "framework": "SOC 2", "clause": "CC6.8", "level": None},
    {"id": "CC7.1", "title": "Detection and Monitoring", "framework": "SOC 2", "clause": "CC7.1", "level": None},
    {"id": "CC7.2", "title": "Anomaly Monitoring", "framework": "SOC 2", "clause": "CC7.2", "level": None},
    {"id": "CC7.3", "title": "Security Event Evaluation", "framework": "SOC 2", "clause": "CC7.3", "level": None},
    {"id": "CC7.4", "title": "Incident Response", "framework": "SOC 2", "clause": "CC7.4", "level": None},
    {"id": "CC7.5", "title": "Recovery from Security Incidents", "framework": "SOC 2", "clause": "CC7.5", "level": None},
    {"id": "CC8.1", "title": "Change Management Process", "framework": "SOC 2", "clause": "CC8.1", "level": None},
    {"id": "CC9.1", "title": "Business Disruption Risk Mitigation", "framework": "SOC 2", "clause": "CC9.1", "level": None},
    {"id": "CC9.2", "title": "Vendor and Business Partner Risk", "framework": "SOC 2", "clause": "CC9.2", "level": None},
    {"id": "SOC-A1.1", "title": "Capacity Management", "framework": "SOC 2", "clause": "A1.1", "level": None},
    {"id": "SOC-A1.2", "title": "Environmental Protections and Recovery Infrastructure", "framework": "SOC 2", "clause": "A1.2", "level": None},
    {"id": "SOC-A1.3", "title": "Recovery and Testing", "framework": "SOC 2", "clause": "A1.3", "level": None},
    {"id": "SOC-C1.1", "title": "Confidential Information Identification", "framework": "SOC 2", "clause": "C1.1", "level": None},
    {"id": "SOC-C1.2", "title": "Confidential Information Disposal", "framework": "SOC 2", "clause": "C1.2", "level": None},
    {"id": "SOC-PI1.1", "title": "Quality Information for Processing", "framework": "SOC 2", "clause": "PI1.1", "level": None},
    {"id": "SOC-PI1.2", "title": "Input Completeness and Accuracy", "framework": "SOC 2", "clause": "PI1.2", "level": None},
    {"id": "SOC-PI1.3", "title": "Processing Policies and Procedures", "framework": "SOC 2", "clause": "PI1.3", "level": None},
    {"id": "SOC-PI1.4", "title": "Output Delivery", "framework": "SOC 2", "clause": "PI1.4", "level": None},
    {"id": "SOC-PI1.5", "title": "Storage of Inputs, Processing, and Outputs", "framework": "SOC 2", "clause": "PI1.5", "level": None},
    {"id": "SOC-P1.1", "title": "Notice to Data Subjects", "framework": "SOC 2", "clause": "P1.1", "level": None},
    {"id": "SOC-P2.1", "title": "Choice and Consent", "framework": "SOC 2", "clause": "P2.1", "level": None},
    {"id": "SOC-P3.1", "title": "Collection", "framework": "SOC 2", "clause": "P3.1", "level": None},
    {"id": "SOC-P3.2", "title": "Explicit Consent", "framework": "SOC 2", "clause": "P3.2", "level": None},
    {"id": "SOC-P4.1", "title": "Use, Retention, and Disposal", "framework": "SOC 2", "clause": "P4.1", "level": None},
    {"id": "SOC-P4.2", "title": "Retention", "framework": "SOC 2", "clause": "P4.2", "level": None},
    {"id": "SOC-P4.3", "title": "Secure Disposal", "framework": "SOC 2", "clause": "P4.3", "level": None},
    {"id": "SOC-P5.1", "title": "Access", "framework": "SOC 2", "clause": "P5.1", "level": None},
    {"id": "SOC-P5.2", "title": "Correction", "framework": "SOC 2", "clause": "P5.2", "level": None},
    {"id": "SOC-P6.1", "title": "Disclosure and Notification", "framework": "SOC 2", "clause": "P6.1", "level": None},
    {"id": "SOC-P6.2", "title": "Record of Authorized Disclosures", "framework": "SOC 2", "clause": "P6.2", "level": None},
    {"id": "SOC-P6.3", "title": "Record of Unauthorized Disclosures", "framework": "SOC 2", "clause": "P6.3", "level": None},
    {"id": "SOC-P6.4", "title": "Vendor Privacy Commitments", "framework": "SOC 2", "clause": "P6.4", "level": None},
    {"id": "SOC-P6.5", "title": "Vendor Breach Notification Commitments", "framework": "SOC 2", "clause": "P6.5", "level": None},
    {"id": "SOC-P6.6", "title": "Breach and Incident Notification", "framework": "SOC 2", "clause": "P6.6", "level": None},
    {"id": "SOC-P6.7", "title": "Accounting of Personal Information", "framework": "SOC 2", "clause": "P6.7", "level": None},
    {"id": "SOC-P7.1", "title": "Quality", "framework": "SOC 2", "clause": "P7.1", "level": None},
    {"id": "SOC-P8.1", "title": "Monitoring and Enforcement", "framework": "SOC 2", "clause": "P8.1", "level": None},

    # EU AI Act (2024/1689) — curated set, mirrors apps/aigovernance/core/ai_controls_catalog.py
    # ═══════════════════════════════════════════════════════════════
    {"id": "EU-5", "title": "Prohibited AI Practices", "framework": "EU AI Act", "clause": "Art. 5", "level": None},
    {"id": "EU-6", "title": "High-Risk Classification Rules", "framework": "EU AI Act", "clause": "Art. 6", "level": None},
    {"id": "EU-8", "title": "Compliance with the Requirements", "framework": "EU AI Act", "clause": "Art. 8", "level": None},
    {"id": "EU-46", "title": "Derogation from Conformity Assessment Procedure", "framework": "EU AI Act", "clause": "Art. 46", "level": None},
    {"id": "EU-47", "title": "EU Declaration of Conformity", "framework": "EU AI Act", "clause": "Art. 47", "level": None},
    {"id": "EU-57", "title": "AI Regulatory Sandboxes", "framework": "EU AI Act", "clause": "Art. 57", "level": None},
    {"id": "EU-60", "title": "Real-World Testing Conditions for High-Risk AI", "framework": "EU AI Act", "clause": "Art. 60", "level": None},
    {"id": "EU-9", "title": "Risk Management System", "framework": "EU AI Act", "clause": "Art. 9", "level": None},
    {"id": "EU-10", "title": "Data and Data Governance", "framework": "EU AI Act", "clause": "Art. 10", "level": None},
    {"id": "EU-11", "title": "Technical Documentation", "framework": "EU AI Act", "clause": "Art. 11", "level": None},
    {"id": "EU-12", "title": "Record-Keeping", "framework": "EU AI Act", "clause": "Art. 12", "level": None},
    {"id": "EU-13", "title": "Transparency for Deployers", "framework": "EU AI Act", "clause": "Art. 13", "level": None},
    {"id": "EU-14", "title": "Human Oversight", "framework": "EU AI Act", "clause": "Art. 14", "level": None},
    {"id": "EU-15", "title": "Accuracy, Robustness & Cybersecurity", "framework": "EU AI Act", "clause": "Art. 15", "level": None},
    {"id": "EU-16", "title": "Provider Obligations", "framework": "EU AI Act", "clause": "Art. 16", "level": None},
    {"id": "EU-17", "title": "Quality Management System", "framework": "EU AI Act", "clause": "Art. 17", "level": None},
    {"id": "EU-18", "title": "Documentation Keeping", "framework": "EU AI Act", "clause": "Art. 18", "level": None},
    {"id": "EU-19", "title": "Automatically Generated Logs", "framework": "EU AI Act", "clause": "Art. 19", "level": None},
    {"id": "EU-20", "title": "Corrective Actions", "framework": "EU AI Act", "clause": "Art. 20", "level": None},
    {"id": "EU-21", "title": "Cooperation with Competent Authorities", "framework": "EU AI Act", "clause": "Art. 21", "level": None},
    {"id": "EU-22", "title": "Authorised Representatives of High-Risk AI Providers", "framework": "EU AI Act", "clause": "Art. 22", "level": None},
    {"id": "EU-23", "title": "Obligations of Importers", "framework": "EU AI Act", "clause": "Art. 23", "level": None},
    {"id": "EU-24", "title": "Obligations of Distributors", "framework": "EU AI Act", "clause": "Art. 24", "level": None},
    {"id": "EU-25", "title": "Responsibilities along the AI Value Chain", "framework": "EU AI Act", "clause": "Art. 25", "level": None},
    {"id": "EU-26", "title": "Deployer Obligations", "framework": "EU AI Act", "clause": "Art. 26", "level": None},
    {"id": "EU-27", "title": "Fundamental Rights Impact Assessment", "framework": "EU AI Act", "clause": "Art. 27", "level": None},
    {"id": "EU-43", "title": "Conformity Assessment", "framework": "EU AI Act", "clause": "Art. 43", "level": None},
    {"id": "EU-48", "title": "CE Marking", "framework": "EU AI Act", "clause": "Art. 48", "level": None},
    {"id": "EU-49", "title": "Registration in EU Database", "framework": "EU AI Act", "clause": "Art. 49", "level": None},
    {"id": "EU-50", "title": "Transparency for Certain AI Systems", "framework": "EU AI Act", "clause": "Art. 50", "level": None},
    {"id": "EU-51", "title": "GPAI Systemic Risk Classification", "framework": "EU AI Act", "clause": "Art. 51", "level": None},
    {"id": "EU-52", "title": "Procedure for Systemic Risk Designation", "framework": "EU AI Act", "clause": "Art. 52", "level": None},
    {"id": "EU-53", "title": "Obligations for GPAI Model Providers", "framework": "EU AI Act", "clause": "Art. 53", "level": None},
    {"id": "EU-54", "title": "Authorised Representatives of GPAI Providers", "framework": "EU AI Act", "clause": "Art. 54", "level": None},
    {"id": "EU-55", "title": "GPAI Providers with Systemic Risk Obligations", "framework": "EU AI Act", "clause": "Art. 55", "level": None},
    {"id": "EU-56", "title": "Codes of Practice", "framework": "EU AI Act", "clause": "Art. 56", "level": None},
    {"id": "EU-61", "title": "Informed Consent for Real-World Testing", "framework": "EU AI Act", "clause": "Art. 61", "level": None},
    {"id": "EU-71", "title": "EU Database for High-Risk AI Systems", "framework": "EU AI Act", "clause": "Art. 71", "level": None},
    {"id": "EU-72", "title": "Post-Market Monitoring", "framework": "EU AI Act", "clause": "Art. 72", "level": None},
    {"id": "EU-73", "title": "Serious Incident Reporting", "framework": "EU AI Act", "clause": "Art. 73", "level": None},

    # OWASP Top 10 for LLM Applications 2025 — 10 risks
    {"id": "OWASP-LLM-1", "title": "Prompt Injection", "framework": "OWASP LLM Top 10", "clause": "LLM01:2025", "level": None},
    {"id": "OWASP-LLM-2", "title": "Sensitive Information Disclosure", "framework": "OWASP LLM Top 10", "clause": "LLM02:2025", "level": None},
    {"id": "OWASP-LLM-3", "title": "Supply Chain", "framework": "OWASP LLM Top 10", "clause": "LLM03:2025", "level": None},
    {"id": "OWASP-LLM-4", "title": "Data and Model Poisoning", "framework": "OWASP LLM Top 10", "clause": "LLM04:2025", "level": None},
    {"id": "OWASP-LLM-5", "title": "Improper Output Handling", "framework": "OWASP LLM Top 10", "clause": "LLM05:2025", "level": None},
    {"id": "OWASP-LLM-6", "title": "Excessive Agency", "framework": "OWASP LLM Top 10", "clause": "LLM06:2025", "level": None},
    {"id": "OWASP-LLM-7", "title": "System Prompt Leakage", "framework": "OWASP LLM Top 10", "clause": "LLM07:2025", "level": None},
    {"id": "OWASP-LLM-8", "title": "Vector and Embedding Weaknesses", "framework": "OWASP LLM Top 10", "clause": "LLM08:2025", "level": None},
    {"id": "OWASP-LLM-9", "title": "Misinformation", "framework": "OWASP LLM Top 10", "clause": "LLM09:2025", "level": None},
    {"id": "OWASP-LLM-10", "title": "Unbounded Consumption", "framework": "OWASP LLM Top 10", "clause": "LLM10:2025", "level": None},

    # OWASP Agentic AI Security Top 10 (2026) — 10 risks
    {"id": "OWASP-1", "title": "Agent Goal Hijack", "framework": "OWASP Agentic", "clause": "ASI01", "level": None},
    {"id": "OWASP-2", "title": "Tool Misuse and Exploitation", "framework": "OWASP Agentic", "clause": "ASI02", "level": None},
    {"id": "OWASP-3", "title": "Identity and Privilege Abuse", "framework": "OWASP Agentic", "clause": "ASI03", "level": None},
    {"id": "OWASP-4", "title": "Agentic Supply Chain Vulnerabilities", "framework": "OWASP Agentic", "clause": "ASI04", "level": None},
    {"id": "OWASP-5", "title": "Unexpected Code Execution (RCE)", "framework": "OWASP Agentic", "clause": "ASI05", "level": None},
    {"id": "OWASP-6", "title": "Memory & Context Poisoning", "framework": "OWASP Agentic", "clause": "ASI06", "level": None},
    {"id": "OWASP-7", "title": "Insecure Inter-Agent Communication", "framework": "OWASP Agentic", "clause": "ASI07", "level": None},
    {"id": "OWASP-8", "title": "Cascading Failures", "framework": "OWASP Agentic", "clause": "ASI08", "level": None},
    {"id": "OWASP-9", "title": "Human-Agent Trust Exploitation", "framework": "OWASP Agentic", "clause": "ASI09", "level": None},
    {"id": "OWASP-10", "title": "Rogue Agents", "framework": "OWASP Agentic", "clause": "ASI10", "level": None},

    # NIST AI RMF 1.0 — 72 subcategories (verbatim from AI 100-1 Tables 1-4)
    {"id": "NIST-GOVERN-1.1", "title": "Legal and regulatory requirements involving AI are understood, managed, and documented.", "framework": "NIST AI RMF", "clause": "GOVERN 1.1", "level": None},
    {"id": "NIST-GOVERN-1.2", "title": "The characteristics of trustworthy AI are integrated into organizational policies, processes, procedures, and practices.", "framework": "NIST AI RMF", "clause": "GOVERN 1.2", "level": None},
    {"id": "NIST-GOVERN-1.3", "title": "Processes, procedures, and practices are in place to determine the needed level of risk management activities based on the organization’s risk tolerance.", "framework": "NIST AI RMF", "clause": "GOVERN 1.3", "level": None},
    {"id": "NIST-GOVERN-1.4", "title": "The risk management process and its outcomes are established through transparent policies, procedures, and other controls based on organizational risk priorities.", "framework": "NIST AI RMF", "clause": "GOVERN 1.4", "level": None},
    {"id": "NIST-GOVERN-1.5", "title": "Ongoing monitoring and periodic review of the risk management process and its outcomes are planned and organizational roles and responsibilities clearly defined, including determining the frequency of periodic review.", "framework": "NIST AI RMF", "clause": "GOVERN 1.5", "level": None},
    {"id": "NIST-GOVERN-1.6", "title": "Mechanisms are in place to inventory AI systems and are resourced according to organizational risk priorities.", "framework": "NIST AI RMF", "clause": "GOVERN 1.6", "level": None},
    {"id": "NIST-GOVERN-1.7", "title": "Processes and procedures are in place for decommissioning and phasing out AI systems safely and in a manner that does not increase risks or decrease the organization’s trustworthiness.", "framework": "NIST AI RMF", "clause": "GOVERN 1.7", "level": None},
    {"id": "NIST-GOVERN-2.1", "title": "Roles and responsibilities and lines of communication related to mapping, measuring, and managing AI risks are documented and are clear to individuals and teams throughout the organization.", "framework": "NIST AI RMF", "clause": "GOVERN 2.1", "level": None},
    {"id": "NIST-GOVERN-2.2", "title": "The organization’s personnel and partners receive AI risk management training to enable them to perform their duties and responsibilities consistent with related policies, procedures, and agreements.", "framework": "NIST AI RMF", "clause": "GOVERN 2.2", "level": None},
    {"id": "NIST-GOVERN-2.3", "title": "Executive leadership of the organization takes responsibility for decisions about risks associated with AI system development and deployment.", "framework": "NIST AI RMF", "clause": "GOVERN 2.3", "level": None},
    {"id": "NIST-GOVERN-3.1", "title": "Decision-making related to mapping, measuring, and managing AI risks throughout the lifecycle is informed by a diverse team (e.g., diversity of demographics, disciplines, experience, expertise, and backgrounds).", "framework": "NIST AI RMF", "clause": "GOVERN 3.1", "level": None},
    {"id": "NIST-GOVERN-3.2", "title": "Policies and procedures are in place to define and differentiate roles and responsibilities for human-AI configurations and oversight of AI systems.", "framework": "NIST AI RMF", "clause": "GOVERN 3.2", "level": None},
    {"id": "NIST-GOVERN-4.1", "title": "Organizational policies and practices are in place to foster a critical thinking and safety-first mindset in the design, development, deployment, and uses of AI systems to minimize potential negative impacts.", "framework": "NIST AI RMF", "clause": "GOVERN 4.1", "level": None},
    {"id": "NIST-GOVERN-4.2", "title": "Organizational teams document the risks and potential impacts of the AI technology they design, develop, deploy, evaluate, and use, and they communicate about the impacts more broadly.", "framework": "NIST AI RMF", "clause": "GOVERN 4.2", "level": None},
    {"id": "NIST-GOVERN-4.3", "title": "Organizational practices are in place to enable AI testing, identification of incidents, and information sharing.", "framework": "NIST AI RMF", "clause": "GOVERN 4.3", "level": None},
    {"id": "NIST-GOVERN-5.1", "title": "Organizational policies and practices are in place to collect, consider, prioritize, and integrate feedback from those external to the team that developed or deployed the AI system regarding the potential individual and societal impacts related to AI risks.", "framework": "NIST AI RMF", "clause": "GOVERN 5.1", "level": None},
    {"id": "NIST-GOVERN-5.2", "title": "Mechanisms are established to enable the team that developed or deployed AI systems to regularly incorporate adjudicated feedback from relevant AI actors into system design and implementation.", "framework": "NIST AI RMF", "clause": "GOVERN 5.2", "level": None},
    {"id": "NIST-GOVERN-6.1", "title": "Policies and procedures are in place that address AI risks associated with third-party entities, including risks of infringement of a third-party’s intellectual property or other rights.", "framework": "NIST AI RMF", "clause": "GOVERN 6.1", "level": None},
    {"id": "NIST-GOVERN-6.2", "title": "Contingency processes are in place to handle failures or incidents in third-party data or AI systems deemed to be high-risk.", "framework": "NIST AI RMF", "clause": "GOVERN 6.2", "level": None},
    {"id": "NIST-MANAGE-1.1", "title": "A determination is made as to whether the AI system achieves its intended purposes and stated objectives and whether its development or deployment should proceed.", "framework": "NIST AI RMF", "clause": "MANAGE 1.1", "level": None},
    {"id": "NIST-MANAGE-1.2", "title": "Treatment of documented AI risks is prioritized based on impact, likelihood, and available resources or methods.", "framework": "NIST AI RMF", "clause": "MANAGE 1.2", "level": None},
    {"id": "NIST-MANAGE-1.3", "title": "Responses to the AI risks deemed high priority, as identified by the MAP function, are developed, planned, and documented. Risk response options can include mitigating, transferring, avoiding, or accepting.", "framework": "NIST AI RMF", "clause": "MANAGE 1.3", "level": None},
    {"id": "NIST-MANAGE-1.4", "title": "Negative residual risks (defined as the sum of all unmitigated risks) to both downstream acquirers of AI systems and end users are documented.", "framework": "NIST AI RMF", "clause": "MANAGE 1.4", "level": None},
    {"id": "NIST-MANAGE-2.1", "title": "Resources required to manage AI risks are taken into account – along with viable non-AI alternative systems, approaches, or methods – to reduce the magnitude or likelihood of potential impacts.", "framework": "NIST AI RMF", "clause": "MANAGE 2.1", "level": None},
    {"id": "NIST-MANAGE-2.2", "title": "Mechanisms are in place and applied to sustain the value of deployed AI systems.", "framework": "NIST AI RMF", "clause": "MANAGE 2.2", "level": None},
    {"id": "NIST-MANAGE-2.3", "title": "Procedures are followed to respond to and recover from a previously unknown risk when it is identified.", "framework": "NIST AI RMF", "clause": "MANAGE 2.3", "level": None},
    {"id": "NIST-MANAGE-2.4", "title": "Mechanisms are in place and applied, and responsibilities are assigned and understood, to supersede, disengage, or deactivate AI systems that demonstrate performance or outcomes inconsistent with intended use.", "framework": "NIST AI RMF", "clause": "MANAGE 2.4", "level": None},
    {"id": "NIST-MANAGE-3.1", "title": "AI risks and benefits from third-party resources are regularly monitored, and risk controls are applied and documented.", "framework": "NIST AI RMF", "clause": "MANAGE 3.1", "level": None},
    {"id": "NIST-MANAGE-3.2", "title": "Pre-trained models which are used for development are monitored as part of AI system regular monitoring and maintenance.", "framework": "NIST AI RMF", "clause": "MANAGE 3.2", "level": None},
    {"id": "NIST-MANAGE-4.1", "title": "Post-deployment AI system monitoring plans are implemented, including mechanisms for capturing and evaluating input from users and other relevant AI actors, appeal and override, decommissioning, incident response, recovery, and change management.", "framework": "NIST AI RMF", "clause": "MANAGE 4.1", "level": None},
    {"id": "NIST-MANAGE-4.2", "title": "Measurable activities for continual improvements are integrated into AI system updates and include regular engagement with interested parties, including relevant AI actors.", "framework": "NIST AI RMF", "clause": "MANAGE 4.2", "level": None},
    {"id": "NIST-MANAGE-4.3", "title": "Incidents and errors are communicated to relevant AI actors, including affected communities. Processes for tracking, responding to, and recovering from incidents and errors are followed and documented.", "framework": "NIST AI RMF", "clause": "MANAGE 4.3", "level": None},
    {"id": "NIST-MAP-1.1", "title": "Intended purposes, potentially beneficial uses, context- specific laws, norms and expectations, and prospective settings in which the AI system will be deployed are understood and documented. Considerations include: the specific set or types of users along with their expectations; potential positive and negative impacts of system uses to individuals, communities, organizations, society, and the planet; assumptions and related limitations about AI system purposes, uses, and risks across the development or product AI lifecycle; and related TEVV and system metrics.", "framework": "NIST AI RMF", "clause": "MAP 1.1", "level": None},
    {"id": "NIST-MAP-1.2", "title": "Interdisciplinary AI actors, competencies, skills, and capacities for establishing context reflect demographic diversity and broad domain and user experience expertise, and their participation is documented. Opportunities for interdisciplinary collaboration are prioritized.", "framework": "NIST AI RMF", "clause": "MAP 1.2", "level": None},
    {"id": "NIST-MAP-1.3", "title": "The organization’s mission and relevant goals for AI technology are understood and documented.", "framework": "NIST AI RMF", "clause": "MAP 1.3", "level": None},
    {"id": "NIST-MAP-1.4", "title": "The business value or context of business use has been clearly defined or – in the case of assessing existing AI systems – re-evaluated.", "framework": "NIST AI RMF", "clause": "MAP 1.4", "level": None},
    {"id": "NIST-MAP-1.5", "title": "Organizational risk tolerances are determined and documented.", "framework": "NIST AI RMF", "clause": "MAP 1.5", "level": None},
    {"id": "NIST-MAP-1.6", "title": "System requirements (e.g., “the system shall respect the privacy of its users”) are elicited from and understood by relevant AI actors. Design decisions take socio-technical implications into account to address AI risks.", "framework": "NIST AI RMF", "clause": "MAP 1.6", "level": None},
    {"id": "NIST-MAP-2.1", "title": "The specific tasks and methods used to implement the tasks that the AI system will support are defined (e.g., classifiers, generative models, recommenders).", "framework": "NIST AI RMF", "clause": "MAP 2.1", "level": None},
    {"id": "NIST-MAP-2.2", "title": "Information about the AI system’s knowledge limits and how system output may be utilized and overseen by humans is documented. Documentation provides sufficient information to assist relevant AI actors when making decisions and taking subsequent actions.", "framework": "NIST AI RMF", "clause": "MAP 2.2", "level": None},
    {"id": "NIST-MAP-2.3", "title": "Scientific integrity and TEVV considerations are identified and documented, including those related to experimental design, data collection and selection (e.g., availability, representativeness, suitability), system trustworthiness, and construct validation.", "framework": "NIST AI RMF", "clause": "MAP 2.3", "level": None},
    {"id": "NIST-MAP-3.1", "title": "Potential benefits of intended AI system functionality and performance are examined and documented.", "framework": "NIST AI RMF", "clause": "MAP 3.1", "level": None},
    {"id": "NIST-MAP-3.2", "title": "Potential costs, including non-monetary costs, which result from expected or realized AI errors or system functionality and trustworthiness – as connected to organizational risk tolerance – are examined and documented.", "framework": "NIST AI RMF", "clause": "MAP 3.2", "level": None},
    {"id": "NIST-MAP-3.3", "title": "Targeted application scope is specified and documented based on the system’s capability, established context, and AI system categorization.", "framework": "NIST AI RMF", "clause": "MAP 3.3", "level": None},
    {"id": "NIST-MAP-3.4", "title": "Processes for operator and practitioner proficiency with AI system performance and trustworthiness – and relevant technical standards and certifications – are defined, assessed, and documented.", "framework": "NIST AI RMF", "clause": "MAP 3.4", "level": None},
    {"id": "NIST-MAP-3.5", "title": "Processes for human oversight are defined, assessed, and documented in accordance with organizational policies from the GOVERN function.", "framework": "NIST AI RMF", "clause": "MAP 3.5", "level": None},
    {"id": "NIST-MAP-4.1", "title": "Approaches for mapping AI technology and legal risks of its components – including the use of third-party data or software – are in place, followed, and documented, as are risks of infringement of a third party’s intellectual property or other rights.", "framework": "NIST AI RMF", "clause": "MAP 4.1", "level": None},
    {"id": "NIST-MAP-4.2", "title": "Internal risk controls for components of the AI system, including third-party AI technologies, are identified and documented.", "framework": "NIST AI RMF", "clause": "MAP 4.2", "level": None},
    {"id": "NIST-MAP-5.1", "title": "Likelihood and magnitude of each identified impact (both potentially beneficial and harmful) based on expected use, past uses of AI systems in similar contexts, public incident reports, feedback from those external to the team that developed or deployed the AI system, or other data are identified and documented.", "framework": "NIST AI RMF", "clause": "MAP 5.1", "level": None},
    {"id": "NIST-MAP-5.2", "title": "Practices and personnel for supporting regular engagement with relevant AI actors and integrating feedback about positive, negative, and unanticipated impacts are in place and documented.", "framework": "NIST AI RMF", "clause": "MAP 5.2", "level": None},
    {"id": "NIST-MEASURE-1.1", "title": "Approaches and metrics for measurement of AI risks enumerated during the MAP function are selected for implementation starting with the most significant AI risks. The risks or trustworthiness characteristics that will not – or cannot – be measured are properly documented.", "framework": "NIST AI RMF", "clause": "MEASURE 1.1", "level": None},
    {"id": "NIST-MEASURE-1.2", "title": "Appropriateness of AI metrics and effectiveness of existing controls are regularly assessed and updated, including reports of errors and potential impacts on affected communities.", "framework": "NIST AI RMF", "clause": "MEASURE 1.2", "level": None},
    {"id": "NIST-MEASURE-1.3", "title": "Internal experts who did not serve as front-line developers for the system and/or independent assessors are involved in regular assessments and updates. Domain experts, users, AI actors external to the team that developed or deployed the AI system, and affected communities are consulted in support of assessments as necessary per organizational risk tolerance.", "framework": "NIST AI RMF", "clause": "MEASURE 1.3", "level": None},
    {"id": "NIST-MEASURE-2.1", "title": "Test sets, metrics, and details about the tools used during TEVV are documented.", "framework": "NIST AI RMF", "clause": "MEASURE 2.1", "level": None},
    {"id": "NIST-MEASURE-2.2", "title": "Evaluations involving human subjects meet applicable requirements (including human subject protection) and are representative of the relevant population.", "framework": "NIST AI RMF", "clause": "MEASURE 2.2", "level": None},
    {"id": "NIST-MEASURE-2.3", "title": "AI system performance or assurance criteria are measured qualitatively or quantitatively and demonstrated for conditions similar to deployment setting(s). Measures are documented.", "framework": "NIST AI RMF", "clause": "MEASURE 2.3", "level": None},
    {"id": "NIST-MEASURE-2.4", "title": "The functionality and behavior of the AI system and its components – as identified in the MAP function – are onitored when in production.", "framework": "NIST AI RMF", "clause": "MEASURE 2.4", "level": None},
    {"id": "NIST-MEASURE-2.5", "title": "The AI system to be deployed is demonstrated to be valid and reliable. Limitations of the generalizability beyond the conditions under which the technology was developed are documented.", "framework": "NIST AI RMF", "clause": "MEASURE 2.5", "level": None},
    {"id": "NIST-MEASURE-2.6", "title": "The AI system is evaluated regularly for safety risks – as identified in the MAP function. The AI system to be deployed is demonstrated to be safe, its residual negative risk does not exceed the risk tolerance, and it can fail safely, particularly if made to operate beyond its knowledge limits. Safety metrics reflect system reliability and robustness, real-time monitoring, and response times for AI system failures.", "framework": "NIST AI RMF", "clause": "MEASURE 2.6", "level": None},
    {"id": "NIST-MEASURE-2.7", "title": "AI system security and resilience – as identified in the MAP function – are evaluated and documented.", "framework": "NIST AI RMF", "clause": "MEASURE 2.7", "level": None},
    {"id": "NIST-MEASURE-2.8", "title": "Risks associated with transparency and accountability – as identified in the MAP function – are examined and documented.", "framework": "NIST AI RMF", "clause": "MEASURE 2.8", "level": None},
    {"id": "NIST-MEASURE-2.9", "title": "The AI model is explained, validated, and documented, and AI system output is interpreted within its context – as identified in the MAP function – to inform responsible use and governance.", "framework": "NIST AI RMF", "clause": "MEASURE 2.9", "level": None},
    {"id": "NIST-MEASURE-2.10", "title": "Privacy risk of the AI system – as identified in the MAP function – is examined and documented.", "framework": "NIST AI RMF", "clause": "MEASURE 2.10", "level": None},
    {"id": "NIST-MEASURE-2.11", "title": "Fairness and bias – as identified in the MAP function – are evaluated and results are documented.", "framework": "NIST AI RMF", "clause": "MEASURE 2.11", "level": None},
    {"id": "NIST-MEASURE-2.12", "title": "Environmental impact and sustainability of AI model training and management activities – as identified in the MAP function – are assessed and documented.", "framework": "NIST AI RMF", "clause": "MEASURE 2.12", "level": None},
    {"id": "NIST-MEASURE-2.13", "title": "Effectiveness of the employed TEVV metrics and processes in the MEASURE function are evaluated and documented.", "framework": "NIST AI RMF", "clause": "MEASURE 2.13", "level": None},
    {"id": "NIST-MEASURE-3.1", "title": "Approaches, personnel, and documentation are in place to regularly identify and track existing, unanticipated, and emergent AI risks based on factors such as intended and actual performance in deployed contexts.", "framework": "NIST AI RMF", "clause": "MEASURE 3.1", "level": None},
    {"id": "NIST-MEASURE-3.2", "title": "Risk tracking approaches are considered for settings where AI risks are difficult to assess using currently available measurement techniques or where metrics are not yet available.", "framework": "NIST AI RMF", "clause": "MEASURE 3.2", "level": None},
    {"id": "NIST-MEASURE-3.3", "title": "Feedback processes for end users and impacted communities to report problems and appeal system outcomes are established and integrated into AI system evaluation metrics.", "framework": "NIST AI RMF", "clause": "MEASURE 3.3", "level": None},
    {"id": "NIST-MEASURE-4.1", "title": "Measurement approaches for identifying AI risks are connected to deployment context(s) and informed through consultation with domain experts and other end users. Approaches are documented.", "framework": "NIST AI RMF", "clause": "MEASURE 4.1", "level": None},
    {"id": "NIST-MEASURE-4.2", "title": "Measurement results regarding AI system trustworthiness in deployment context(s) and across the AI lifecycle are informed by input from domain experts and relevant AI actors to validate whether the system is performing consistently as intended. Results are documented.", "framework": "NIST AI RMF", "clause": "MEASURE 4.2", "level": None},
    {"id": "NIST-MEASURE-4.3", "title": "Measurable performance improvements or declines based on consultations with relevant AI actors, including affected communities, and field data about context-relevant risks and trustworthiness characteristics are identified and documented.", "framework": "NIST AI RMF", "clause": "MEASURE 4.3", "level": None},

    # ISO 42001 (23 clauses 4.1-10.2 + 9 Annex A objectives A.2-A.10)
    # mirrors apps/aigovernance/core/ai_controls_catalog.py
    # ═══════════════════════════════════════════════════════════════
    {"id": "ISO-4.1", "title": "External & Internal Context", "framework": "ISO 42001", "clause": "4.1", "level": None},
    {"id": "ISO-4.2", "title": "Interested Parties", "framework": "ISO 42001", "clause": "4.2", "level": None},
    {"id": "ISO-4.3", "title": "AI Management System Scope", "framework": "ISO 42001", "clause": "4.3", "level": None},
    {"id": "ISO-4.4", "title": "AI Management System", "framework": "ISO 42001", "clause": "4.4", "level": None},
    {"id": "ISO-5.1", "title": "Leadership & Commitment", "framework": "ISO 42001", "clause": "5.1", "level": None},
    {"id": "ISO-5.2", "title": "AI Policy", "framework": "ISO 42001", "clause": "5.2", "level": None},
    {"id": "ISO-5.3", "title": "Roles & Responsibilities", "framework": "ISO 42001", "clause": "5.3", "level": None},
    {"id": "ISO-6.1", "title": "Risk-Based Planning", "framework": "ISO 42001", "clause": "6.1", "level": None},
    {"id": "ISO-6.2", "title": "AI Objectives", "framework": "ISO 42001", "clause": "6.2", "level": None},
    {"id": "ISO-7.1", "title": "Resources", "framework": "ISO 42001", "clause": "7.1", "level": None},
    {"id": "ISO-7.2", "title": "Competence", "framework": "ISO 42001", "clause": "7.2", "level": None},
    {"id": "ISO-7.3", "title": "Awareness", "framework": "ISO 42001", "clause": "7.3", "level": None},
    {"id": "ISO-7.4", "title": "Communication", "framework": "ISO 42001", "clause": "7.4", "level": None},
    {"id": "ISO-7.5", "title": "Documented Information", "framework": "ISO 42001", "clause": "7.5", "level": None},
    {"id": "ISO-8.1", "title": "Operational Planning & Control", "framework": "ISO 42001", "clause": "8.1", "level": None},
    {"id": "ISO-8.2", "title": "AI Risk Assessment", "framework": "ISO 42001", "clause": "8.2", "level": None},
    {"id": "ISO-8.3", "title": "AI Risk Treatment", "framework": "ISO 42001", "clause": "8.3", "level": None},
    {"id": "ISO-8.4", "title": "AI System Impact Assessment", "framework": "ISO 42001", "clause": "8.4", "level": None},
    {"id": "ISO-9.1", "title": "Monitoring & Measurement", "framework": "ISO 42001", "clause": "9.1", "level": None},
    {"id": "ISO-9.2", "title": "Internal Audit", "framework": "ISO 42001", "clause": "9.2", "level": None},
    {"id": "ISO-9.3", "title": "Management Review", "framework": "ISO 42001", "clause": "9.3", "level": None},
    {"id": "ISO-10.1", "title": "Continual Improvement", "framework": "ISO 42001", "clause": "10.1", "level": None},
    {"id": "ISO-10.2", "title": "Nonconformity & Corrective Action", "framework": "ISO 42001", "clause": "10.2", "level": None},
    {"id": "ISO-A.2", "title": "Policies related to AI", "framework": "ISO 42001", "clause": "A.2", "level": None},
    {"id": "ISO-A.3", "title": "Internal organization", "framework": "ISO 42001", "clause": "A.3", "level": None},
    {"id": "ISO-A.4", "title": "Resources for AI systems", "framework": "ISO 42001", "clause": "A.4", "level": None},
    {"id": "ISO-A.5", "title": "Assessing impacts of AI systems", "framework": "ISO 42001", "clause": "A.5", "level": None},
    {"id": "ISO-A.6", "title": "AI system life cycle", "framework": "ISO 42001", "clause": "A.6", "level": None},
    {"id": "ISO-A.7", "title": "Data for AI systems", "framework": "ISO 42001", "clause": "A.7", "level": None},
    {"id": "ISO-A.8", "title": "Information for interested parties of AI systems", "framework": "ISO 42001", "clause": "A.8", "level": None},
    {"id": "ISO-A.9", "title": "Use of AI systems", "framework": "ISO 42001", "clause": "A.9", "level": None},
    {"id": "ISO-A.10", "title": "Third-party and customer relationships", "framework": "ISO 42001", "clause": "A.10", "level": None},

    # ISO 42001 Annex A controls (38, verbatim from Table A.1)
    {"id": "ISO-A.2.2", "title": "AI policy", "framework": "ISO 42001", "clause": "A.2.2", "level": None},
    {"id": "ISO-A.2.3", "title": "Alignment with other organizational policies", "framework": "ISO 42001", "clause": "A.2.3", "level": None},
    {"id": "ISO-A.2.4", "title": "Review of the AI policy", "framework": "ISO 42001", "clause": "A.2.4", "level": None},
    {"id": "ISO-A.3.2", "title": "AI roles and responsibilities", "framework": "ISO 42001", "clause": "A.3.2", "level": None},
    {"id": "ISO-A.3.3", "title": "Reporting of concerns", "framework": "ISO 42001", "clause": "A.3.3", "level": None},
    {"id": "ISO-A.4.2", "title": "Resource documentation", "framework": "ISO 42001", "clause": "A.4.2", "level": None},
    {"id": "ISO-A.4.3", "title": "Data resources", "framework": "ISO 42001", "clause": "A.4.3", "level": None},
    {"id": "ISO-A.4.4", "title": "Tooling resources", "framework": "ISO 42001", "clause": "A.4.4", "level": None},
    {"id": "ISO-A.4.5", "title": "System and computing resources", "framework": "ISO 42001", "clause": "A.4.5", "level": None},
    {"id": "ISO-A.4.6", "title": "Human resources", "framework": "ISO 42001", "clause": "A.4.6", "level": None},
    {"id": "ISO-A.5.2", "title": "AI system impact assessment process", "framework": "ISO 42001", "clause": "A.5.2", "level": None},
    {"id": "ISO-A.5.3", "title": "Documentation of AI system impact assessments", "framework": "ISO 42001", "clause": "A.5.3", "level": None},
    {"id": "ISO-A.5.4", "title": "Assessing AI system impact on individuals or groups of individuals", "framework": "ISO 42001", "clause": "A.5.4", "level": None},
    {"id": "ISO-A.5.5", "title": "Assessing societal impacts of AI systems", "framework": "ISO 42001", "clause": "A.5.5", "level": None},
    {"id": "ISO-A.6.1.2", "title": "Objectives for responsible development of AI system", "framework": "ISO 42001", "clause": "A.6.1.2", "level": None},
    {"id": "ISO-A.6.1.3", "title": "Processes for responsible AI system design and development", "framework": "ISO 42001", "clause": "A.6.1.3", "level": None},
    {"id": "ISO-A.6.2.2", "title": "AI system requirements and specification", "framework": "ISO 42001", "clause": "A.6.2.2", "level": None},
    {"id": "ISO-A.6.2.3", "title": "Documentation of AI system design and development", "framework": "ISO 42001", "clause": "A.6.2.3", "level": None},
    {"id": "ISO-A.6.2.4", "title": "AI system verification and validation", "framework": "ISO 42001", "clause": "A.6.2.4", "level": None},
    {"id": "ISO-A.6.2.5", "title": "AI system deployment", "framework": "ISO 42001", "clause": "A.6.2.5", "level": None},
    {"id": "ISO-A.6.2.6", "title": "AI system operation and monitoring", "framework": "ISO 42001", "clause": "A.6.2.6", "level": None},
    {"id": "ISO-A.6.2.7", "title": "AI system technical documentation", "framework": "ISO 42001", "clause": "A.6.2.7", "level": None},
    {"id": "ISO-A.6.2.8", "title": "AI system recording of event logs", "framework": "ISO 42001", "clause": "A.6.2.8", "level": None},
    {"id": "ISO-A.7.2", "title": "Data for development and enhancement of AI system", "framework": "ISO 42001", "clause": "A.7.2", "level": None},
    {"id": "ISO-A.7.3", "title": "Acquisition of data", "framework": "ISO 42001", "clause": "A.7.3", "level": None},
    {"id": "ISO-A.7.4", "title": "Quality of data for AI systems", "framework": "ISO 42001", "clause": "A.7.4", "level": None},
    {"id": "ISO-A.7.5", "title": "Data provenance", "framework": "ISO 42001", "clause": "A.7.5", "level": None},
    {"id": "ISO-A.7.6", "title": "Data preparation", "framework": "ISO 42001", "clause": "A.7.6", "level": None},
    {"id": "ISO-A.8.2", "title": "System documentation and information for users", "framework": "ISO 42001", "clause": "A.8.2", "level": None},
    {"id": "ISO-A.8.3", "title": "External reporting", "framework": "ISO 42001", "clause": "A.8.3", "level": None},
    {"id": "ISO-A.8.4", "title": "Communication of incidents", "framework": "ISO 42001", "clause": "A.8.4", "level": None},
    {"id": "ISO-A.8.5", "title": "Information for interested parties", "framework": "ISO 42001", "clause": "A.8.5", "level": None},
    {"id": "ISO-A.9.2", "title": "Processes for responsible use of AI systems", "framework": "ISO 42001", "clause": "A.9.2", "level": None},
    {"id": "ISO-A.9.3", "title": "Objectives for responsible use of AI system", "framework": "ISO 42001", "clause": "A.9.3", "level": None},
    {"id": "ISO-A.9.4", "title": "Intended use of the AI system", "framework": "ISO 42001", "clause": "A.9.4", "level": None},
    {"id": "ISO-A.10.2", "title": "Allocating responsibilities", "framework": "ISO 42001", "clause": "A.10.2", "level": None},
    {"id": "ISO-A.10.3", "title": "Suppliers", "framework": "ISO 42001", "clause": "A.10.3", "level": None},
    {"id": "ISO-A.10.4", "title": "Customers", "framework": "ISO 42001", "clause": "A.10.4", "level": None},

    # ═══════════════════════════════════════════════════════════════
    # ISO 27001 (framework-scoped ids ISO27K-*) (ISMS clauses 4.1–10.2 + Annex A controls A.5.1–A.8.34)
    # (mirrors apps/iso27001/core/controls.py — keep in sync)
    # ═══════════════════════════════════════════════════════════════
    {"id": "ISO27K-4.1", "title": "Understanding the organization and its context", "framework": "ISO 27001", "clause": "4.1", "level": None},
    {"id": "ISO27K-4.2", "title": "Understanding the needs and expectations of interested parties", "framework": "ISO 27001", "clause": "4.2", "level": None},
    {"id": "ISO27K-4.3", "title": "Determining the scope of the information security management system", "framework": "ISO 27001", "clause": "4.3", "level": None},
    {"id": "ISO27K-4.4", "title": "Information security management system", "framework": "ISO 27001", "clause": "4.4", "level": None},
    {"id": "ISO27K-5.1", "title": "Leadership and commitment", "framework": "ISO 27001", "clause": "5.1", "level": None},
    {"id": "ISO27K-5.2", "title": "Policy", "framework": "ISO 27001", "clause": "5.2", "level": None},
    {"id": "ISO27K-5.3", "title": "Organizational roles, responsibilities and authorities", "framework": "ISO 27001", "clause": "5.3", "level": None},
    {"id": "ISO27K-6.1", "title": "Actions to address risks and opportunities", "framework": "ISO 27001", "clause": "6.1", "level": None},
    {"id": "ISO27K-6.1.1", "title": "General (actions to address risks and opportunities)", "framework": "ISO 27001", "clause": "6.1.1", "level": None},
    {"id": "ISO27K-6.1.2", "title": "Information security risk assessment", "framework": "ISO 27001", "clause": "6.1.2", "level": None},
    {"id": "ISO27K-6.1.3", "title": "Information security risk treatment", "framework": "ISO 27001", "clause": "6.1.3", "level": None},
    {"id": "ISO27K-6.2", "title": "Information security objectives and planning to achieve them", "framework": "ISO 27001", "clause": "6.2", "level": None},
    {"id": "ISO27K-6.3", "title": "Planning of changes", "framework": "ISO 27001", "clause": "6.3", "level": None},
    {"id": "ISO27K-7.1", "title": "Resources", "framework": "ISO 27001", "clause": "7.1", "level": None},
    {"id": "ISO27K-7.2", "title": "Competence", "framework": "ISO 27001", "clause": "7.2", "level": None},
    {"id": "ISO27K-7.3", "title": "Awareness", "framework": "ISO 27001", "clause": "7.3", "level": None},
    {"id": "ISO27K-7.4", "title": "Communication", "framework": "ISO 27001", "clause": "7.4", "level": None},
    {"id": "ISO27K-7.5", "title": "Documented information", "framework": "ISO 27001", "clause": "7.5", "level": None},
    {"id": "ISO27K-8.1", "title": "Operational planning and control", "framework": "ISO 27001", "clause": "8.1", "level": None},
    {"id": "ISO27K-8.2", "title": "Information security risk assessment", "framework": "ISO 27001", "clause": "8.2", "level": None},
    {"id": "ISO27K-8.3", "title": "Information security risk treatment", "framework": "ISO 27001", "clause": "8.3", "level": None},
    {"id": "ISO27K-9.1", "title": "Monitoring, measurement, analysis and evaluation", "framework": "ISO 27001", "clause": "9.1", "level": None},
    {"id": "ISO27K-9.2", "title": "Internal audit", "framework": "ISO 27001", "clause": "9.2", "level": None},
    {"id": "ISO27K-9.2.1", "title": "General (internal audit)", "framework": "ISO 27001", "clause": "9.2.1", "level": None},
    {"id": "ISO27K-9.2.2", "title": "Internal audit programme", "framework": "ISO 27001", "clause": "9.2.2", "level": None},
    {"id": "ISO27K-9.3", "title": "Management review", "framework": "ISO 27001", "clause": "9.3", "level": None},
    {"id": "ISO27K-9.3.1", "title": "General (management review)", "framework": "ISO 27001", "clause": "9.3.1", "level": None},
    {"id": "ISO27K-9.3.2", "title": "Management review inputs", "framework": "ISO 27001", "clause": "9.3.2", "level": None},
    {"id": "ISO27K-9.3.3", "title": "Management review results", "framework": "ISO 27001", "clause": "9.3.3", "level": None},
    {"id": "ISO27K-10.1", "title": "Continual improvement", "framework": "ISO 27001", "clause": "10.1", "level": None},
    {"id": "ISO27K-10.2", "title": "Nonconformity and corrective action", "framework": "ISO 27001", "clause": "10.2", "level": None},
    {"id": "ISO27K-A.5.1", "title": "Policies for information security", "framework": "ISO 27001", "clause": "A.5.1", "level": None},
    {"id": "ISO27K-A.5.2", "title": "Information security roles and responsibilities", "framework": "ISO 27001", "clause": "A.5.2", "level": None},
    {"id": "ISO27K-A.5.3", "title": "Segregation of duties", "framework": "ISO 27001", "clause": "A.5.3", "level": None},
    {"id": "ISO27K-A.5.4", "title": "Management responsibilities", "framework": "ISO 27001", "clause": "A.5.4", "level": None},
    {"id": "ISO27K-A.5.5", "title": "Contact with authorities", "framework": "ISO 27001", "clause": "A.5.5", "level": None},
    {"id": "ISO27K-A.5.6", "title": "Contact with special interest groups", "framework": "ISO 27001", "clause": "A.5.6", "level": None},
    {"id": "ISO27K-A.5.7", "title": "Threat intelligence", "framework": "ISO 27001", "clause": "A.5.7", "level": None},
    {"id": "ISO27K-A.5.8", "title": "Information security in project management", "framework": "ISO 27001", "clause": "A.5.8", "level": None},
    {"id": "ISO27K-A.5.9", "title": "Inventory of information and other associated assets", "framework": "ISO 27001", "clause": "A.5.9", "level": None},
    {"id": "ISO27K-A.5.10", "title": "Acceptable use of information and other associated assets", "framework": "ISO 27001", "clause": "A.5.10", "level": None},
    {"id": "ISO27K-A.5.11", "title": "Return of assets", "framework": "ISO 27001", "clause": "A.5.11", "level": None},
    {"id": "ISO27K-A.5.12", "title": "Classification of information", "framework": "ISO 27001", "clause": "A.5.12", "level": None},
    {"id": "ISO27K-A.5.13", "title": "Labelling of information", "framework": "ISO 27001", "clause": "A.5.13", "level": None},
    {"id": "ISO27K-A.5.14", "title": "Information transfer", "framework": "ISO 27001", "clause": "A.5.14", "level": None},
    {"id": "ISO27K-A.5.15", "title": "Access control", "framework": "ISO 27001", "clause": "A.5.15", "level": None},
    {"id": "ISO27K-A.5.16", "title": "Identity management", "framework": "ISO 27001", "clause": "A.5.16", "level": None},
    {"id": "ISO27K-A.5.17", "title": "Authentication information", "framework": "ISO 27001", "clause": "A.5.17", "level": None},
    {"id": "ISO27K-A.5.18", "title": "Access rights", "framework": "ISO 27001", "clause": "A.5.18", "level": None},
    {"id": "ISO27K-A.5.19", "title": "Information security in supplier relationships", "framework": "ISO 27001", "clause": "A.5.19", "level": None},
    {"id": "ISO27K-A.5.20", "title": "Addressing information security within supplier agreements", "framework": "ISO 27001", "clause": "A.5.20", "level": None},
    {"id": "ISO27K-A.5.21", "title": "Managing information security in the information and communication technology (ICT) supply chain", "framework": "ISO 27001", "clause": "A.5.21", "level": None},
    {"id": "ISO27K-A.5.22", "title": "Monitoring, review and change management of supplier services", "framework": "ISO 27001", "clause": "A.5.22", "level": None},
    {"id": "ISO27K-A.5.23", "title": "Information security for use of cloud services", "framework": "ISO 27001", "clause": "A.5.23", "level": None},
    {"id": "ISO27K-A.5.24", "title": "Information security incident management planning and preparation", "framework": "ISO 27001", "clause": "A.5.24", "level": None},
    {"id": "ISO27K-A.5.25", "title": "Assessment and decision on information security events", "framework": "ISO 27001", "clause": "A.5.25", "level": None},
    {"id": "ISO27K-A.5.26", "title": "Response to information security incidents", "framework": "ISO 27001", "clause": "A.5.26", "level": None},
    {"id": "ISO27K-A.5.27", "title": "Learning from information security incidents", "framework": "ISO 27001", "clause": "A.5.27", "level": None},
    {"id": "ISO27K-A.5.28", "title": "Collection of evidence", "framework": "ISO 27001", "clause": "A.5.28", "level": None},
    {"id": "ISO27K-A.5.29", "title": "Information security during disruption", "framework": "ISO 27001", "clause": "A.5.29", "level": None},
    {"id": "ISO27K-A.5.30", "title": "ICT readiness for business continuity", "framework": "ISO 27001", "clause": "A.5.30", "level": None},
    {"id": "ISO27K-A.5.31", "title": "Legal, statutory, regulatory and contractual requirements", "framework": "ISO 27001", "clause": "A.5.31", "level": None},
    {"id": "ISO27K-A.5.32", "title": "Intellectual property rights", "framework": "ISO 27001", "clause": "A.5.32", "level": None},
    {"id": "ISO27K-A.5.33", "title": "Protection of records", "framework": "ISO 27001", "clause": "A.5.33", "level": None},
    {"id": "ISO27K-A.5.34", "title": "Privacy and protection of personal identifiable information (PII)", "framework": "ISO 27001", "clause": "A.5.34", "level": None},
    {"id": "ISO27K-A.5.35", "title": "Independent review of information security", "framework": "ISO 27001", "clause": "A.5.35", "level": None},
    {"id": "ISO27K-A.5.36", "title": "Compliance with policies, rules and standards for information security", "framework": "ISO 27001", "clause": "A.5.36", "level": None},
    {"id": "ISO27K-A.5.37", "title": "Documented operating procedures", "framework": "ISO 27001", "clause": "A.5.37", "level": None},
    {"id": "ISO27K-A.6.1", "title": "Screening", "framework": "ISO 27001", "clause": "A.6.1", "level": None},
    {"id": "ISO27K-A.6.2", "title": "Terms and conditions of employment", "framework": "ISO 27001", "clause": "A.6.2", "level": None},
    {"id": "ISO27K-A.6.3", "title": "Information security awareness, education and training", "framework": "ISO 27001", "clause": "A.6.3", "level": None},
    {"id": "ISO27K-A.6.4", "title": "Disciplinary process", "framework": "ISO 27001", "clause": "A.6.4", "level": None},
    {"id": "ISO27K-A.6.5", "title": "Responsibilities after termination or change of employment", "framework": "ISO 27001", "clause": "A.6.5", "level": None},
    {"id": "ISO27K-A.6.6", "title": "Confidentiality or non-disclosure agreements", "framework": "ISO 27001", "clause": "A.6.6", "level": None},
    {"id": "ISO27K-A.6.7", "title": "Remote working", "framework": "ISO 27001", "clause": "A.6.7", "level": None},
    {"id": "ISO27K-A.6.8", "title": "Information security event reporting", "framework": "ISO 27001", "clause": "A.6.8", "level": None},
    {"id": "ISO27K-A.7.1", "title": "Physical security perimeters", "framework": "ISO 27001", "clause": "A.7.1", "level": None},
    {"id": "ISO27K-A.7.2", "title": "Physical entry", "framework": "ISO 27001", "clause": "A.7.2", "level": None},
    {"id": "ISO27K-A.7.3", "title": "Securing offices, rooms and facilities", "framework": "ISO 27001", "clause": "A.7.3", "level": None},
    {"id": "ISO27K-A.7.4", "title": "Physical security monitoring", "framework": "ISO 27001", "clause": "A.7.4", "level": None},
    {"id": "ISO27K-A.7.5", "title": "Protecting against physical and environmental threats", "framework": "ISO 27001", "clause": "A.7.5", "level": None},
    {"id": "ISO27K-A.7.6", "title": "Working in secure areas", "framework": "ISO 27001", "clause": "A.7.6", "level": None},
    {"id": "ISO27K-A.7.7", "title": "Clear desk and clear screen", "framework": "ISO 27001", "clause": "A.7.7", "level": None},
    {"id": "ISO27K-A.7.8", "title": "Equipment siting and protection", "framework": "ISO 27001", "clause": "A.7.8", "level": None},
    {"id": "ISO27K-A.7.9", "title": "Security of assets off-premises", "framework": "ISO 27001", "clause": "A.7.9", "level": None},
    {"id": "ISO27K-A.7.10", "title": "Storage media", "framework": "ISO 27001", "clause": "A.7.10", "level": None},
    {"id": "ISO27K-A.7.11", "title": "Supporting utilities", "framework": "ISO 27001", "clause": "A.7.11", "level": None},
    {"id": "ISO27K-A.7.12", "title": "Cabling security", "framework": "ISO 27001", "clause": "A.7.12", "level": None},
    {"id": "ISO27K-A.7.13", "title": "Equipment maintenance", "framework": "ISO 27001", "clause": "A.7.13", "level": None},
    {"id": "ISO27K-A.7.14", "title": "Secure disposal or re-use of equipment", "framework": "ISO 27001", "clause": "A.7.14", "level": None},
    {"id": "ISO27K-A.8.1", "title": "User endpoint devices", "framework": "ISO 27001", "clause": "A.8.1", "level": None},
    {"id": "ISO27K-A.8.2", "title": "Privileged access rights", "framework": "ISO 27001", "clause": "A.8.2", "level": None},
    {"id": "ISO27K-A.8.3", "title": "Information access restriction", "framework": "ISO 27001", "clause": "A.8.3", "level": None},
    {"id": "ISO27K-A.8.4", "title": "Access to source code", "framework": "ISO 27001", "clause": "A.8.4", "level": None},
    {"id": "ISO27K-A.8.5", "title": "Secure authentication", "framework": "ISO 27001", "clause": "A.8.5", "level": None},
    {"id": "ISO27K-A.8.6", "title": "Capacity management", "framework": "ISO 27001", "clause": "A.8.6", "level": None},
    {"id": "ISO27K-A.8.7", "title": "Protection against malware", "framework": "ISO 27001", "clause": "A.8.7", "level": None},
    {"id": "ISO27K-A.8.8", "title": "Management of technical vulnerabilities", "framework": "ISO 27001", "clause": "A.8.8", "level": None},
    {"id": "ISO27K-A.8.9", "title": "Configuration management", "framework": "ISO 27001", "clause": "A.8.9", "level": None},
    {"id": "ISO27K-A.8.10", "title": "Information deletion", "framework": "ISO 27001", "clause": "A.8.10", "level": None},
    {"id": "ISO27K-A.8.11", "title": "Data masking", "framework": "ISO 27001", "clause": "A.8.11", "level": None},
    {"id": "ISO27K-A.8.12", "title": "Data leakage prevention", "framework": "ISO 27001", "clause": "A.8.12", "level": None},
    {"id": "ISO27K-A.8.13", "title": "Information backup", "framework": "ISO 27001", "clause": "A.8.13", "level": None},
    {"id": "ISO27K-A.8.14", "title": "Redundancy of information processing facilities", "framework": "ISO 27001", "clause": "A.8.14", "level": None},
    {"id": "ISO27K-A.8.15", "title": "Logging", "framework": "ISO 27001", "clause": "A.8.15", "level": None},
    {"id": "ISO27K-A.8.16", "title": "Monitoring activities", "framework": "ISO 27001", "clause": "A.8.16", "level": None},
    {"id": "ISO27K-A.8.17", "title": "Clock synchronization", "framework": "ISO 27001", "clause": "A.8.17", "level": None},
    {"id": "ISO27K-A.8.18", "title": "Use of privileged utility programs", "framework": "ISO 27001", "clause": "A.8.18", "level": None},
    {"id": "ISO27K-A.8.19", "title": "Installation of software on operational systems", "framework": "ISO 27001", "clause": "A.8.19", "level": None},
    {"id": "ISO27K-A.8.20", "title": "Networks security", "framework": "ISO 27001", "clause": "A.8.20", "level": None},
    {"id": "ISO27K-A.8.21", "title": "Security of network services", "framework": "ISO 27001", "clause": "A.8.21", "level": None},
    {"id": "ISO27K-A.8.22", "title": "Segregation of networks", "framework": "ISO 27001", "clause": "A.8.22", "level": None},
    {"id": "ISO27K-A.8.23", "title": "Web filtering", "framework": "ISO 27001", "clause": "A.8.23", "level": None},
    {"id": "ISO27K-A.8.24", "title": "Use of cryptography", "framework": "ISO 27001", "clause": "A.8.24", "level": None},
    {"id": "ISO27K-A.8.25", "title": "Secure development life cycle", "framework": "ISO 27001", "clause": "A.8.25", "level": None},
    {"id": "ISO27K-A.8.26", "title": "Application security requirements", "framework": "ISO 27001", "clause": "A.8.26", "level": None},
    {"id": "ISO27K-A.8.27", "title": "Secure system architecture and engineering principles", "framework": "ISO 27001", "clause": "A.8.27", "level": None},
    {"id": "ISO27K-A.8.28", "title": "Secure coding", "framework": "ISO 27001", "clause": "A.8.28", "level": None},
    {"id": "ISO27K-A.8.29", "title": "Security testing in development and acceptance", "framework": "ISO 27001", "clause": "A.8.29", "level": None},
    {"id": "ISO27K-A.8.30", "title": "Outsourced development", "framework": "ISO 27001", "clause": "A.8.30", "level": None},
    {"id": "ISO27K-A.8.31", "title": "Separation of development, test and production environments", "framework": "ISO 27001", "clause": "A.8.31", "level": None},
    {"id": "ISO27K-A.8.32", "title": "Change management", "framework": "ISO 27001", "clause": "A.8.32", "level": None},
    {"id": "ISO27K-A.8.33", "title": "Test information", "framework": "ISO 27001", "clause": "A.8.33", "level": None},
    {"id": "ISO27K-A.8.34", "title": "Protection of information systems during audit testing", "framework": "ISO 27001", "clause": "A.8.34", "level": None}
]


def list_controls(framework: str | None = None) -> list[dict]:
    if framework:
        return [c for c in CONTROLS_CATALOG if c["framework"] == framework]
    return list(CONTROLS_CATALOG)


def list_frameworks() -> list[str]:
    return sorted(set(c["framework"] for c in CONTROLS_CATALOG))
