"""Faithful paraphrases of the AICPA 2017 TSC Points of Focus.

Source of truth (titles + full sentences): docs/trust-services-criteria-2017.txt/.pdf,
locked verbatim in tsc_2017_official.py. This module carries complete, faithful
paraphrases of every official Point of Focus, in official order, for the OSS catalog
— a CPA must recognise each entry as the same concept as the official title, but the
wording is re-stated rather than copied (AICPA titles are copyrighted; ACCURACY_BACKLOG
SKU 1 requires paraphrase in the Apache-2.0 repo).

Keys: criterion id -> list[str] of paraphrased PoF intents (official order). Count
parity (299 total) is asserted by tests/test_catalog_titles.py.
"""

POF_PARAPHRASES: dict[str, list[str]] = {
    # ── A1 — Additional Criteria for Availability ────────────────────────
    "A1.1": [
        "Track current demand on the system to understand how processing and storage capacity is being consumed.",
        "Project future capacity needs from observed trends and expected business growth.",
        "Adjust staffing, hardware, or cloud provisioning according to those forward-looking estimates.",
    ],
    "A1.2": [
        "Survey the facility and environment for hazards such as fire, flooding, power loss, and severe weather.",
        "Put in place instrumentation or sensors that give early warning of environmental events.",
        "Deploy and keep in working order protective mechanisms like redundant power, climate control, and fire suppression.",
        "Set up alarms that surface anomalies in environmental conditions for review.",
        "Deal with environmental events promptly to limit their effect on availability.",
        "Share findings about environmental events with the right people and reassess how the entity is prepared.",
        "Decide which data is important enough to back up to meet recovery targets.",
        "Run backups on a defined schedule and keep them recoverable.",
        "Store backup copies off site so a single location loss does not destroy them.",
        "Stand up alternate processing infrastructure so core operations can resume during a disruption.",
    ],
    "A1.3": [
        "Exercise the business continuity and recovery plan so procedures are proven, not just written.",
        "Verify that backup data is complete and intact enough to support a full restoration.",
    ],
    # ── C1 — Additional Criteria for Confidentiality ─────────────────────
    "C1.1": [
        "Know which information is confidential so it can be deliberately protected.",
        "Prevent confidential information from being destroyed, whether deliberately or by accident.",
    ],
    "C1.2": [
        "Single out the confidential information that has reached the end of its useful life.",
        "Dispose of confidential information using a method that matches its sensitivity.",
    ],
    # ── CC1 — Control Environment ────────────────────────────────────────
    "CC1.1": [
        "Leadership signals, through example and message, that integrity and ethics are non-negotiable.",
        "Written standards describe the behaviour the organisation expects of its people.",
        "The entity checks how well its people actually live up to those stated standards.",
        "Departures from the code of conduct are caught and corrected without delay.",
        "The same ethical expectations are extended to contractors and to staff supplied by vendors.",
    ],
    "CC1.2": [
        "The board acknowledges and takes on its oversight role for the control environment.",
        "Board members bring the knowledge needed to oversee technology, reporting, and risk.",
        "The board evaluates management free from dependence or undue management influence.",
        "Outside specialists or additional directors are brought in when the board lacks depth.",
    ],
    "CC1.3": [
        "Organisational structure reflects every part of the entity rather than a single unit.",
        "Reporting lines are explicit so authority and escalation are clear.",
        "Authority and responsibility are assigned, described, and kept within sensible limits.",
        "Special requirements are reflected when defining who can decide and who is accountable.",
        "Dealings with outside parties are factored into the design of structure and reporting lines.",
    ],
    "CC1.4": [
        "Hiring and people practices support the entity's ability to reach its objectives.",
        "Skill gaps are spotted and addressed through development, coaching, or reassignment.",
        "The entity draws in, grows, and keeps people who fit its objectives.",
        "Succession is planned for so key roles are never left empty.",
        "An individual's history and background are weighed before they take on a role.",
        "The technical skill needed for a position is an explicit factor in filling it.",
        "Training keeps essential technical competencies current over time.",
    ],
    "CC1.5": [
        "People are answerable for what they do through explicit structures, authority, and duties.",
        "Performance goals, incentives, and rewards align personal effort with entity objectives.",
        "The entity reviews whether its measures and rewards still make sense as conditions change.",
        "Pressures that tempt people to cut corners are recognised and eased.",
        "Actual performance is evaluated and followed by rewards or discipline as warranted.",
    ],
    # ── CC2 — Information and Communication ──────────────────────────────
    "CC2.1": [
        "Define what information the entity needs to run its control system.",
        "Pull in data from inside and outside the organisation as required.",
        "Turn raw data into information that supports the entity's goals.",
        "Protect data quality from capture through every processing step.",
    ],
    "CC2.2": [
        "Details about internal control reach the people who need them.",
        "The board receives the information it needs to exercise oversight.",
        "Confidential channels exist so staff can raise concerns without fear.",
        "The delivery method fits the audience and the sensitivity of the topic.",
        "Duties and expectations are spelled out to whoever must carry them out.",
        "Guidance covers how to report failures, incidents, concerns, and other problems.",
        "Goals and revisions to goals are shared with those affected.",
        "Security knowledge and awareness is actively promoted through communication.",
        "Information about how the system operates and where its boundaries lie is shared.",
        "System objectives are explained to the people who rely on them.",
        "Planned system changes are broadcast to stakeholders in advance.",
    ],
    "CC2.3": [
        "Relevant information is shared with outside parties like customers and suppliers.",
        "Outside parties can reach the entity to provide input or raise issues.",
        "The board stays informed of external matters that bear on internal control.",
        "Dedicated lines let outside parties report concerns separately.",
        "The medium chosen suits the external audience and the subject.",
        "Confidentiality commitments and any changes are communicated externally.",
        "Privacy commitments and any changes are communicated externally.",
        "External parties hear about system operation and its boundaries.",
        "System objectives are made clear to external stakeholders.",
        "External parties understand which system responsibilities are theirs.",
        "Outside parties know how to report system failures, incidents, and concerns.",
    ],
    # ── CC3 — Risk Assessment ────────────────────────────────────────────
    "CC3.1": [
        "Operational goals mirror the strategic choices management has made.",
        "Operational goals respect how much risk management is willing to take on.",
        "Operational goals cover both operations and financial performance.",
        "Operational goals justify how resources are committed.",
        "External financial reporting follows the relevant accounting standards.",
        "Materiality guides what external financial reporting focuses on.",
        "External financial reporting reflects the real activities of the entity.",
        "External financial reporting aligns with established reporting frameworks.",
        "Internal reporting is tuned to the precision decision-makers need.",
        "Internal reporting reflects what the entity actually does.",
        "Internal reporting reflects management's own choices and priorities.",
        "Internal reporting is calibrated to the precision required for decisions.",
        "Internal reporting mirrors the entity's actual activities.",
        "Internal reporting honours external laws and regulations.",
        "Internal reporting weighs management's tolerance for risk.",
        "Broad goals are broken into sub-objectives that make them achievable.",
    ],
    "CC3.2": [
        "Risk is assessed across the whole enterprise, including its subsidiaries, divisions, units, and functions.",
        "Both internal and external factors are weighed for their effect on objectives.",
        "The right levels of management take part in the assessment.",
        "Identified risks are sized by how significant they could be.",
        "A clear response is chosen for each risk the entity faces.",
        "Information assets are ranked by criticality and their threats and weaknesses identified.",
        "Threats and weaknesses introduced by vendors, partners, and others are analysed.",
        "How material a risk is shapes the response selected.",
    ],
    "CC3.3": [
        "The full range of fraud types the entity might face is considered.",
        "Pressures and incentives that could push someone toward fraud are examined.",
        "Loopholes that would let fraud go undetected are sought out.",
        "Attitudes and justifications that lower the barrier to fraud are probed.",
        "Risks tied to IT use and to access to information are part of the fraud analysis.",
    ],
    "CC3.4": [
        "Shifts in the regulatory, economic, and competitive environment are monitored.",
        "Changes to the business model are assessed for their risk impact.",
        "Turnover and changes in leadership are evaluated.",
        "New or modified systems and technology are reviewed for risk.",
        "Shifts in relationships with vendors and business partners are assessed.",
    ],
    # ── CC4 — Monitoring Activities ──────────────────────────────────────
    "CC4.1": [
        "A blend of continuous checks and periodic reviews keeps controls under observation.",
        "How quickly the entity changes guides how often monitoring must happen.",
        "A baseline of expected behaviour is set so deviations are visible.",
        "Evaluators are qualified and understand what they are testing.",
        "Monitoring is woven into normal business operations whenever possible.",
        "The reach and cadence of monitoring change with the level of risk.",
        "Evaluation is performed independently of the people running the controls.",
        "Both ongoing and standalone evaluation methods are available and used appropriately.",
    ],
    "CC4.2": [
        "Evaluation findings are interpreted for what they mean about objectives.",
        "Deficiencies are reported to whoever must take corrective action.",
        "Fixes are followed up to confirm they actually resolve the deficiency.",
    ],
    # ── CC5 — Control Activities ─────────────────────────────────────────
    "CC5.1": [
        "Control selection flows directly out of the risk assessment.",
        "The entity's own circumstances shape which controls it chooses.",
        "The processes that matter most to objectives are identified.",
        "A balanced set of control types—preventive, detective, and others—is used.",
        "Whether a control lives at the entity or operating-unit level is a deliberate choice.",
        "Duties that must not sit with a single person are separated.",
    ],
    "CC5.2": [
        "The reliance of business processes on technology and on general IT controls is mapped.",
        "Controls over the technology infrastructure are established.",
        "Controls over security-management processes are established.",
        "Controls over how technology is acquired, developed, and maintained are established.",
    ],
    "CC5.3": [
        "Policies and procedures translate management's directives into everyday action.",
        "Ownership and accountability for executing policies are explicit.",
        "Controls are performed promptly, not indefinitely deferred.",
        "Failures of policy or procedure trigger corrective action.",
        "The people performing controls are competent to do so.",
        "Policies and procedures are revisited and updated over time.",
    ],
    # ── CC6 — Logical and Physical Access ────────────────────────────────
    "CC6.1": [
        "The entity keeps a current inventory of its information assets.",
        "Logical access to the system and protected data is carefully gated.",
        "Users are identified and verified before access is granted.",
        "Network segmentation is used to limit how far access can spread.",
        "Entry points into the environment are known and controlled.",
        "Access to information assets is limited to what a role legitimately needs.",
        "User identity and authentication mechanisms stay well managed.",
        "Credentials used by infrastructure and software are controlled.",
        "Encryption protects data both when moving and when at rest.",
        "The keys guarding that encryption are themselves protected.",
    ],
    "CC6.2": [
        "Credentials issued for protected assets are kept under control.",
        "When access to an asset is no longer justified, it is withdrawn.",
        "Existing credentials are re-examined to confirm they are still appropriate.",
    ],
    "CC6.3": [
        "Grants and changes to access on protected data follow an authorised process.",
        "Access rights are removed from protected data once they are no longer needed.",
        "Role-based access ties what a person can do to the role they hold.",
        "Access roles and their rules are reviewed on a schedule.",
    ],
    "CC6.4": [
        "Physical access is granted or changed only through controlled steps.",
        "Physical access is rescinded when it is no longer justified.",
        "Physical access lists are reviewed to keep them current.",
    ],
    "CC6.5": [
        "The data and software headed for disposal are identified up front.",
        "Data and software leave the entity's control only when it is safe, with reads and recovery no longer needed.",
    ],
    "CC6.6": [
        "Access from outside the system boundary is tightly constrained.",
        "Identification and authentication credentials are safeguarded.",
        "Higher-risk access requires stronger or additional authentication.",
        "Boundary protections like firewalls and intrusion prevention sit between the entity and outside.",
    ],
    "CC6.7": [
        "Who may transmit, move, or remove information is strictly limited.",
        "Data in motion rides secure channels or encryption to avoid exposure.",
        "Removable media that carries data is protected.",
        "Portable devices that hold or reach data are protected.",
    ],
    "CC6.8": [
        "Only approved applications and software may be installed.",
        "Unofficial changes to software or configuration are made detectable.",
        "Software changes travel through a formal change control process.",
        "Antivirus and anti-malware tools run across the environment.",
        "Assets entering from outside the entity are scanned for malware and rogue software.",
    ],
    # ── CC7 — System Operations ───────────────────────────────────────────
    "CC7.1": [
        "Infrastructure and software are built to defined configuration standards.",
        "Systems are watched for drift away from those standards.",
        "Mechanisms detect when configuration changes without authorisation.",
        "Unknown or unauthorised components are identified when they appear.",
        "Vulnerability scanning happens on a regular, defined basis.",
    ],
    "CC7.2": [
        "Detection is backed by documented policy, procedure, and tooling.",
        "Detection measures are deliberately designed to catch anomalies.",
        "Filters separate real anomalies from background noise.",
        "The monitoring tools themselves are supervised to confirm they keep working.",
    ],
    "CC7.3": [
        "Security incidents draw a defined response rather than ad-hoc action.",
        "Detected events are reported and reviewed with the relevant stakeholders.",
        "Procedure exists for analysing incidents to understand what happened.",
        "Incidents are assessed for their impact on personal information.",
        "What personal information was involved or exposed in an incident is established.",
    ],
    "CC7.4": [
        "Someone is named and made responsible for every part of the incident response program.",
        "Incidents that actively threaten objectives are contained.",
        "Steps are taken to reduce harm from incidents still under way.",
        "The threat from an incident is ended by fixing the cause, removing the threat, or isolating the affected part.",
        "Systems and data are brought back to a working state that supports objectives.",
        "Protocols govern how incidents and the actions taken are communicated to those affected.",
        "The nature of the incident is understood before choosing how to contain it.",
        "Weaknesses that allowed the incident are closed through defined remediation.",
        "Remediation work is documented and reported under the incident response program.",
        "The design of incident response is tested for effectiveness on a periodic basis.",
        "Management periodically looks back over incidents touching security, availability, processing integrity, confidentiality, and privacy.",
        "Where personal information was used or exposed without authorisation, the data subjects are told.",
        "People or organisations behind unauthorised use or disclosure face sanctions.",
    ],
    "CC7.5": [
        "The environment hit by an incident is restored to a working state.",
        "Stakeholders are told what occurred and what it means for them.",
        "The underlying cause of the event is established.",
        "Changes are made so the same failure is harder to repeat.",
        "Lessons from the incident sharpen future response and recovery.",
        "The incident-recovery plan itself is tested on a schedule.",
    ],
    # ── CC8 — Change Management ───────────────────────────────────────────
    "CC8.1": [
        "Change is managed across every stage of the system life cycle.",
        "No change proceeds without prior authorisation.",
        "Changes are designed and built with security considerations included.",
        "A written record captures each change for later reference.",
        "Each change is traceable from request all the way to implementation.",
        "Software is configured to approved specifications.",
        "Changes are tested before being released.",
        "Implementation of a change requires formal approval.",
        "Released changes go out through a controlled deployment process.",
        "Proposed and completed changes are checked to confirm they remain appropriate.",
        "Post-incident changes to infrastructure, data, software, and procedures are identified and managed.",
        "A baseline configuration for the IT estate is captured.",
        "Emergency change paths exist so urgent fixes are not blocked by process.",
        "Confidential information stays protected while changes are made.",
        "Personal information stays protected while changes are made.",
    ],
    # ── CC9 — Risk Mitigation ─────────────────────────────────────────────
    "CC9.1": [
        "What could disrupt operations, and what would soften the blow, is considered up front.",
        "Insurance is weighed as a way to cover the financial side of disruption risk.",
    ],
    "CC9.2": [
        "Up-front requirements define what the entity expects of its vendors and partners.",
        "The risk posed by each vendor and business partner is evaluated.",
        "Clear ownership is assigned for managing vendor and partner relationships.",
        "Communication with vendors and partners follows defined protocols.",
        "Vendor and partner exceptions are handled through a defined process.",
        "Vendor and partner performance is assessed over time.",
        "Problems surfaced during vendor assessments are worked through defined steps.",
        "Ending a vendor or partner relationship follows a defined offboarding path.",
        "Vendors and partners sign up to confidentiality commitments.",
        "The entity verifies vendors and partners actually keep those confidentiality promises.",
        "Privacy commitments are obtained from vendors and partners.",
        "Compliance with those privacy commitments is checked over time.",
    ],
    # ── P1 — Privacy Notice ───────────────────────────────────────────────
    "P1.1": [
        "Data subjects are told about the entity's privacy practices.",
        "A notice spells out what personal information is collected and how it is used.",
        "The notice makes clear which entities and activities are covered.",
        "The notice is written plainly and visibly, not buried or vague.",
    ],
    "P2.1": [
        "The choices data subjects have over their personal information are communicated.",
        "What happens if someone refuses or withdraws consent is explained.",
        "Consent is obtained in the form the situation calls for—implicit or explicit.",
        "Fresh consent is documented whenever information is put to a new purpose.",
        "Sensitive information is only handled with explicit consent.",
        "Moving personal information to another party also requires consent.",
    ],
    "P3.1": [
        "Collection is capped at what the entity genuinely needs and is allowed to have.",
        "Information is gathered fairly and within the law.",
        "Data is pulled only from sources the entity can trust.",
        "The individual is told when more of their information is being gathered.",
    ],
    "P3.2": [
        "Holding sensitive information requires explicit consent.",
        "Consent to retain information is captured in writing.",
    ],
    "P4.1": [
        "Personal information is used only for the purposes that were stated and authorised.",
    ],
    "P4.2": [
        "Retention follows the entity's stated objectives and policy.",
        "Personal information is safeguarded for the whole time it is kept.",
    ],
    "P4.3": [
        "Requests to delete information are captured and flagged for action.",
        "Removal takes the form required—disposal, destruction, or redaction.",
        "Destruction matches the retention and disposal the entity has committed to.",
    ],
    "P5.1": [
        "The person asking for access is verified before their data is released.",
        "Data subjects are allowed to see the personal information held on them.",
        "Information is handed over in terms they can follow and within a reasonable time.",
        "If access is refused, the individual is told so.",
    ],
    "P5.2": [
        "A refused access request comes with an explanation.",
        "Data subjects can have their information updated or corrected.",
        "A refused correction request comes with an explanation.",
    ],
    "P6.1": [
        "Parties that receive disclosures are briefed on the entity's privacy policies.",
        "Information is handed to others only when doing so is justified.",
        "Disclosures go only to parties that are appropriate recipients.",
        "Sharing information for fresh purposes and new uses happens only on a proper basis.",
    ],
    "P6.2": [
        "A record is kept of every authorised disclosure.",
    ],
    "P6.3": [
        "A record is kept of unauthorised disclosures that were detected or reported.",
    ],
    "P6.4": [
        "Disclosures are confined to parties that are appropriate recipients.",
        "Third-party misuse of personal information is corrected and its effects addressed.",
    ],
    "P6.5": [
        "Third-party misuse of personal information is corrected and its effects addressed.",
        "Actual or suspected unauthorised disclosures are reported.",
    ],
    "P6.6": [
        "Third-party misuse of personal information is corrected and its effects addressed.",
        "Breaches and incidents touching personal information are notified to the right people.",
    ],
    "P6.7": [
        "The types of personal information held and how each is handled is documented.",
        "Requests from data subjects for information are captured, recognised, and answered.",
    ],
    "P7.1": [
        "The personal information on file is kept accurate and complete.",
        "Held information stays relevant to the purpose it was collected for.",
    ],
    "P8.1": [
        "Data subjects know how to reach the entity with questions, complaints, and disputes.",
        "A defined process handles inquiries, complaints, and disputes.",
        "Each complaint is resolved and the outcome documented and shared with the individual.",
        "Privacy compliance reviews are documented and their results reported to management.",
        "Privacy noncompliance is documented and reported, with corrective and disciplinary measures applied when required.",
        "Continual procedures keep watch on the controls over personal information and trigger timely fixes.",
    ],
    # ── PI1 — Additional Criteria for Processing Integrity ───────────────
    "PI1.1": [
        "The information requirements behind products and services are specified.",
        "The data needed to deliver a product or service is defined.",
        "What information the user needs to get value from a good or product is defined.",
    ],
    "PI1.2": [
        "The expected shape and quality of processing inputs are defined.",
        "Incoming inputs are checked against those defined expectations.",
        "A record of system inputs is created and maintained.",
    ],
    "PI1.3": [
        "The specifications the processing must meet are defined.",
        "The activities the system carries out are clearly defined.",
        "Errors that slip into production are caught and corrected.",
        "System processing activity is logged.",
        "Inputs are processed in line with defined specifications.",
    ],
    "PI1.4": [
        "Output is guarded against unauthorised use or alteration.",
        "Output goes only to the people meant to receive it.",
        "Output is delivered in full and without errors.",
        "A record of output activity is created and maintained.",
    ],
    "PI1.5": [
        "Stored items—inputs, in-process data, and outputs—are protected.",
        "System records are archived and safeguarded.",
        "Data is stored completely, accurately, and as designed.",
        "A record of storage activity is created and maintained.",
    ],
}
