"""ISO 27001 auditor pack — clauses 9.2 (internal audit) and 9.3 (management review).

Exports:
- internal audit report (docx)
- management-review minutes (docx)
- nonconformity / corrective-action register (xlsx)
- zip of the three
"""

from __future__ import annotations

import io
import zipfile
from datetime import date
from typing import Any, Dict, List


ISO_FRAMEWORK = "ISO 27001"


def _audits() -> List[Dict[str, Any]]:
    try:
        from audit_center.store import list_audits

        rows = list_audits(framework=ISO_FRAMEWORK) or []
        if not rows:
            rows = list_audits() or []
        return [r for r in rows if (r.get("framework") or ISO_FRAMEWORK) in (ISO_FRAMEWORK, "ISO27001", "iso27001", "")]
    except Exception:
        return []


def _reviews() -> List[Dict[str, Any]]:
    try:
        from management_review.store import list_reviews

        return list_reviews() or []
    except Exception:
        return []


def _findings_with_actions() -> List[Dict[str, Any]]:
    try:
        from findings.store import list_actions, list_findings

        rows = list_findings(framework=ISO_FRAMEWORK) or []
    except Exception:
        return []
    out = []
    for f in rows:
        try:
            from findings.store import list_actions

            actions = list_actions(f.get("id") or "") or []
        except Exception:
            actions = []
        item = dict(f)
        item["actions"] = actions
        out.append(item)
    return out


def export_internal_audit_report_docx() -> bytes:
    """Clause 9.2 internal audit report."""
    from docx import Document
    from docx.shared import Pt

    audits = _audits()
    findings = [f for f in _findings_with_actions() if (f.get("source") or "") == "audit"]

    doc = Document()
    doc.add_heading("ISO/IEC 27001:2022 — Internal Audit Report", 0)
    doc.add_paragraph(
        "This report records internal audits of the information security management system "
        "in accordance with clause 9.2."
    )
    doc.add_paragraph(f"Generated: {date.today().isoformat()}")

    doc.add_heading("1. Audit programme", level=1)
    if not audits:
        doc.add_paragraph("No ISO 27001 internal audits have been recorded yet.")
    else:
        table = doc.add_table(rows=1, cols=6)
        table.style = "Table Grid"
        for i, h in enumerate(["Title", "Type", "Status", "Auditor", "Start", "End"]):
            table.rows[0].cells[i].text = h
            for run in table.rows[0].cells[i].paragraphs[0].runs:
                run.bold = True
                run.font.size = Pt(9)
        for a in audits:
            cells = table.add_row().cells
            cells[0].text = a.get("title") or ""
            cells[1].text = a.get("audit_type") or ""
            cells[2].text = a.get("status") or ""
            cells[3].text = a.get("auditor_name") or ""
            cells[4].text = a.get("start_date") or ""
            cells[5].text = a.get("end_date") or ""
            for cell in cells:
                for p in cell.paragraphs:
                    for run in p.runs:
                        run.font.size = Pt(8)
        for a in audits:
            doc.add_heading(a.get("title") or "Audit", level=2)
            if a.get("scope_notes"):
                doc.add_paragraph(f"Scope: {a['scope_notes']}")
            if a.get("preparation_notes"):
                doc.add_paragraph(f"Notes: {a['preparation_notes']}")

    doc.add_heading("2. Nonconformities raised from audit", level=1)
    if not findings:
        doc.add_paragraph("No audit-sourced nonconformities recorded.")
    else:
        for f in findings:
            doc.add_paragraph(
                f"{f.get('title') or 'Finding'} — {f.get('severity') or ''} / {f.get('status') or ''}",
                style="List Bullet",
            )
            if f.get("description"):
                doc.add_paragraph(f.get("description"))

    doc.add_paragraph("")
    doc.add_paragraph("Generated by Khestra — ISO/IEC 27001 internal audit (clause 9.2).")
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def export_management_review_minutes_docx() -> bytes:
    """Clause 9.3 management review minutes."""
    from docx import Document
    from docx.shared import Pt

    reviews = _reviews()
    doc = Document()
    doc.add_heading("ISO/IEC 27001:2022 — Management Review Minutes", 0)
    doc.add_paragraph(
        "Top management review of the ISMS in accordance with clause 9.3 "
        "(inputs 9.3.2, outputs 9.3.3)."
    )
    doc.add_paragraph(f"Generated: {date.today().isoformat()}")

    if not reviews:
        doc.add_paragraph("No management reviews have been recorded yet.")
    for r in reviews:
        title = r.get("title") or "Management review"
        doc.add_heading(f"{title} ({r.get('date') or 'undated'})", level=1)
        doc.add_paragraph(f"Status: {r.get('status') or '—'}")
        attendees = r.get("attendees") or []
        if attendees:
            names = []
            for a in attendees:
                if isinstance(a, dict):
                    names.append(a.get("name") or a.get("email") or str(a))
                else:
                    names.append(str(a))
            doc.add_paragraph("Attendees: " + ", ".join(names))
        if r.get("minutes"):
            doc.add_heading("Minutes", level=2)
            doc.add_paragraph(r["minutes"])
        inputs = r.get("inputs") or []
        if inputs:
            doc.add_heading("Inputs (clause 9.3.2)", level=2)
            for item in inputs:
                if isinstance(item, dict):
                    label = item.get("label") or item.get("key") or "Input"
                    notes = item.get("notes") or item.get("value") or ""
                    doc.add_paragraph(f"{label}: {notes}" if notes else str(label), style="List Bullet")
                else:
                    doc.add_paragraph(str(item), style="List Bullet")
        outputs = r.get("outputs") or []
        if outputs:
            doc.add_heading("Outputs / decisions (clause 9.3.3)", level=2)
            for item in outputs:
                if isinstance(item, dict):
                    label = item.get("title") or item.get("category") or "Decision"
                    notes = item.get("notes") or item.get("description") or ""
                    doc.add_paragraph(f"{label}: {notes}" if notes else str(label), style="List Bullet")
                else:
                    doc.add_paragraph(str(item), style="List Bullet")
        actions = r.get("action_items") or []
        if actions:
            doc.add_heading("Action items", level=2)
            table = doc.add_table(rows=1, cols=3)
            table.style = "Table Grid"
            for i, h in enumerate(["Action", "Owner", "Due"]):
                table.rows[0].cells[i].text = h
                for run in table.rows[0].cells[i].paragraphs[0].runs:
                    run.bold = True
                    run.font.size = Pt(9)
            for item in actions:
                if not isinstance(item, dict):
                    item = {"title": str(item)}
                cells = table.add_row().cells
                cells[0].text = item.get("title") or item.get("action") or ""
                cells[1].text = item.get("owner") or ""
                cells[2].text = item.get("due_date") or item.get("target_date") or ""

    doc.add_paragraph("")
    doc.add_paragraph("Generated by Khestra — ISO/IEC 27001 management review (clause 9.3).")
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def export_nc_capa_xlsx() -> bytes:
    """Nonconformity and corrective-action register."""
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    rows = _findings_with_actions()
    wb = Workbook()
    ws = wb.active
    ws.title = "NC-CAPA Register"
    headers = [
        "Finding ID", "Title", "Severity", "Status", "Source", "Controls",
        "Owner", "Corrective action", "Action owner", "Action status", "Target date",
    ]
    ws.append(headers)
    header_fill = PatternFill("solid", fgColor="1F4E79")
    for cell in ws[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = header_fill
        cell.alignment = Alignment(vertical="center")

    if not rows:
        ws.append(["", "No nonconformities recorded", "", "", "", "", "", "", "", "", ""])
    for f in rows:
        controls = f.get("control_ids") or []
        if isinstance(controls, str):
            control_s = controls
        else:
            control_s = ", ".join(str(c) for c in controls)
        actions = f.get("actions") or []
        if not actions:
            ws.append([
                f.get("id") or "",
                f.get("title") or "",
                f.get("severity") or "",
                f.get("status") or "",
                f.get("source") or "",
                control_s,
                f.get("owner") or "",
                "",
                "",
                "",
                "",
            ])
            continue
        for a in actions:
            ws.append([
                f.get("id") or "",
                f.get("title") or "",
                f.get("severity") or "",
                f.get("status") or "",
                f.get("source") or "",
                control_s,
                f.get("owner") or "",
                a.get("title") or "",
                a.get("owner") or "",
                a.get("status") or "",
                a.get("target_date") or "",
            ])

    widths = [14, 36, 12, 14, 12, 18, 16, 36, 16, 14, 14]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w
    ws.freeze_panes = "A2"

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def export_auditor_pack_zip() -> bytes:
    """Clause 9.2 + 9.3 pack: audit report, MR minutes, NC/CAPA register."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.txt", (
            "Khestra ISO/IEC 27001 auditor pack\n"
            f"Generated: {date.today().isoformat()}\n\n"
            "  01-internal-audit-report.docx     clause 9.2\n"
            "  02-management-review-minutes.docx clause 9.3\n"
            "  03-nc-capa-register.xlsx          nonconformities and corrective actions\n"
        ))
        zf.writestr("01-internal-audit-report.docx", export_internal_audit_report_docx())
        zf.writestr("02-management-review-minutes.docx", export_management_review_minutes_docx())
        zf.writestr("03-nc-capa-register.xlsx", export_nc_capa_xlsx())
    return buf.getvalue()
